"use client";
import { useCallback, useEffect, useState } from "react";
import type { report } from "@/lib/content-income/store";
type Json<T> = T extends Date ? string : T extends Array<infer V> ? Json<V>[] : T extends object ? { [P in keyof T]: Json<T[P]> } : T;
type Data = Json<Awaited<ReturnType<typeof report>>>;
const money = (c: number | null) => c === null ? "Not reported" : (c / 100).toLocaleString("en-US", { style: "currency", currency: "USD" });
const date = (s: string) => new Date(s).toLocaleString("en-US", { timeZone: "America/Chicago", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" });
const num = (n: number | null) => n === null ? "—" : n.toLocaleString("en-US");
const statusLabel = (s: string) => ({ unknown: "Not verified", not_invited: "Waiting for invitation", invited: "Invitation received", active: "Active", restricted: "Restricted", sending: "Sending", uncertain: "Check published result", skipped: "Skipped · slot passed", failed: "Needs attention", posted: "Published", queued: "Scheduled" }[s] || s);

export function ContentIncome() {
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [filter, setFilter] = useState("posted");
  const load = useCallback(async () => { try { const r = await fetch("/api/hq/content-income", { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw Error(d.error); setData(d); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not load report"); } }, []);
  useEffect(() => { void load(); const t = setInterval(load, 60000); return () => clearInterval(t); }, [load]);
  async function action(body: unknown) { setBusy(true); try { const r = await fetch("/api/hq/content-income", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const d = await r.json(); if (!r.ok) throw Error(d.error); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not save change"); } finally { setBusy(false); } }
  if (!data) return <main className="income"><h1>Content income</h1><p role="status">{error || "Loading publishing and earnings…"}</p><button onClick={() => void load()}>Refresh</button></main>;
  const a = data.account;
  const issues = [a.metricsError, a.earningsError, a.qualifiedViewsError, ...data.posts.filter(p => ["uncertain", "failed"].includes(p.status)).map(p => p.error)].filter(Boolean);
  const posts = data.posts.filter(p => filter === "all" || (filter === "attention" ? ["uncertain", "failed"].includes(p.status) : p.status === filter)).sort((x, y) => filter === "queued" ? Date.parse(x.scheduledAt) - Date.parse(y.scheduledAt) : Date.parse(y.scheduledAt) - Date.parse(x.scheduledAt));
  return <main className="income">
    <header><div><a href="/hq?tab=growth">← Growth HQ</a><p className="income-eyebrow">TREASURE HAULS · ORIGINAL CONTENT</p><h1>Make the posts count.</h1><p>Publishing, audience growth and real earnings in one place.</p></div><div className="income-actions"><button disabled={busy} onClick={() => void action({ action: "sync" })}>Refresh from Meta</button><button disabled={busy} className="income-primary" onClick={() => void action(a.startedAt ? { action: "pause", paused: !a.paused } : { action: "enable" })}>{a.paused ? "Start publishing" : "Pause publishing"}</button></div></header>
    {error && <p className="income-alert" role="alert">{error}</p>}
    <section className="income-metrics" aria-label="Earnings and audience"><article><span>Meta estimated earnings · 30 days</span><strong>{money(data.estimatedCents)}</strong><small>{data.earningDays.length ? `${data.earningDays.length} daily values returned by Meta · not a payout` : "No earnings values received"}</small></article><article><span>Confirmed cash received</span><strong>{data.receipts.length ? money(data.totals.paidCents) : "Not recorded"}</strong><small>{data.receipts.length ? `${money(data.totals.pendingCents)} pending · receipts kept separately` : "Add a payout receipt when it arrives"}</small></article><article><span>Followers</span><strong>{num(a.followers)}</strong><small>{a.connectionCheckedAt ? `Meta checked ${date(a.connectionCheckedAt)}` : "Account not checked"}</small></article><article><span>Original posts published</span><strong>{data.counts.find(c => c.status === "posted")?._count._all || 0}</strong><small>{data.counts.find(c => c.status === "queued")?._count._all || 0} scheduled · no generation charges</small></article></section>
    <section className="income-panel"><div className="income-panel-heading"><div><h2>{a.label}</h2><p>{a.paused ? "Publishing paused" : "Publishing enabled"} · Posts at 9:30 AM and 2:30 PM Central, alternating which format goes first. Up to two feed posts per day, shared with show promotion and clips.</p></div><a href="https://business.facebook.com/latest/monetization?asset_id=1156652300855210" target="_blank" rel="noreferrer">Open Meta monetization ↗</a></div><div className="income-status"><span>Content monetization <b>{statusLabel(a.programStatus)}</b></span><span>Payout setup <b>{a.payoutsVerified ? "Verified by owner" : "Not verified"}</b></span><span>Worker <b>{a.heartbeatAt ? `Checked ${date(a.heartbeatAt)}` : "Waiting for first run"}</b></span></div>{a.programEvidence && <p className="income-note">Owner evidence: {a.programEvidence}{a.programVerifiedAt && ` · ${date(a.programVerifiedAt)}`}</p>}<p className="income-note">{data.topics} original resale topics. Text and image versions run a week apart. Confirmed show previews keep their feed slot; missed slots expire.</p></section>
    {!!issues.length && <section className="income-panel income-attention"><h2>What needs attention</h2>{[...new Set(issues)].map((issue, i) => <p key={i}>{issue}</p>)}<p>Missing permissions and missing measurements stay visible. They are not counted as zero views.</p></section>}
    <section className="income-panel"><h2>What’s earning attention</h2>{data.winners.length ? data.winners.map(p => <p key={p.id}><b>{p.headline}</b> · {p.format} · {num(p.shares)} shares · {num(p.follows)} follows · {num(p.views)} views</p>) : <p>Waiting for measured results. Add post views from Meta to compare shares and follows per 1,000 views.</p>}</section>
    <section className="income-panel"><div className="income-panel-heading"><h2>Actual posts and next experiments</h2><select aria-label="Filter experiments" value={filter} onChange={e => setFilter(e.target.value)}>{[["posted", "Published"], ["queued", "Scheduled"], ["attention", "Needs attention"], ["all", "All records"]].map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></div><div className="income-posts">{posts.slice(0, 30).map(p => <article key={p.id} className="income-post"><div><span>{p.format.toUpperCase()} · {statusLabel(p.status)}</span><time>{date(p.scheduledAt)}</time></div><h3>{p.headline}</h3><p>{num(p.views)} views · {num(p.shares)} shares · {num(p.follows)} follows · {money(p.earningsCents)} estimated earnings</p>{p.url && <a href={p.url} target="_blank" rel="noreferrer">Open published post ↗</a>}<details><summary>Copy and artwork</summary><p className="income-copy">{p.caption}</p>{p.format === "image" && <a href={`/api/content-income/art/${p.id}`} target="_blank" rel="noreferrer">Preview image ↗</a>}</details>{p.error && <p className="income-alert">{p.error}</p>}{p.metricsError && <p className="income-note">Metrics: {p.metricsError}</p>}</article>)}</div>{!posts.length && <p>No posts in this view yet.</p>}</section>
    <section className="income-panel"><h2>Record the evidence</h2><p>Meta daily earnings are estimates. A bank payout is recorded once by its statement reference.</p><details><summary>Confirm monetization and payout setup</summary><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void action({ action: "verify", programStatus: f.get("status"), payoutsVerified: f.get("payout") === "on", evidence: f.get("evidence") }); }}><label>Program status<select name="status" defaultValue={a.programStatus}>{[["unknown", "Not verified"], ["not_invited", "Waiting for invitation"], ["invited", "Invitation received"], ["active", "Active"], ["restricted", "Restricted"]].map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label><label><input name="payout" type="checkbox" defaultChecked={a.payoutsVerified} /> Payout setup verified in Meta</label><label>Dashboard evidence<input name="evidence" required minLength={5} maxLength={500} placeholder="What Meta shows, and date checked" /></label><button disabled={busy}>Save verification</button></form></details>
    <details><summary>Add a payout or pending statement</summary><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void action({ action: "receipt", externalId: f.get("reference"), amountCents: Math.round(Number(f.get("amount")) * 100), period: f.get("period"), status: f.get("status"), evidence: f.get("evidence") }); }}><label>Statement reference<input name="reference" required minLength={3} /></label><label>Amount (USD)<input name="amount" type="number" min="0" step="0.01" required /></label><label>Earnings month<input name="period" type="month" required /></label><label>Status<select name="status"><option value="pending">Pending</option><option value="paid">Paid to bank</option><option value="reversed">Reversed</option></select></label><label>Evidence<input name="evidence" required minLength={5} maxLength={500} placeholder="Statement or bank transaction reference" /></label><button disabled={busy}>Record statement</button></form></details>
    <details><summary>Add measured post performance</summary><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const read = (key: string) => f.get(key) === "" ? null : Number(f.get(key)); void action({ action: "metrics", postId: f.get("post"), views: read("views"), qualifiedViews: read("qualifiedViews"), reactions: read("reactions"), comments: read("comments"), shares: read("shares"), follows: read("follows"), earningsCents: f.get("earnings") === "" ? null : Math.round(Number(f.get("earnings")) * 100), measuredAt: new Date().toISOString(), evidence: f.get("evidence") }); }}><label>Published experiment<select name="post" required><option value="">Choose a post</option>{data.posts.filter(p => p.status === "posted").map(p => <option value={p.id} key={p.id}>{p.format} · {p.headline}</option>)}</select></label>{["views", "qualifiedViews", "reactions", "comments", "shares", "follows", "earnings"].map(key => <label key={key}>{key === "earnings" ? "Estimated post earnings (USD)" : key === "qualifiedViews" ? "Qualified views" : key}<input name={key} type="number" min="0" step={key === "earnings" ? "0.01" : "1"} /></label>)}<label>Evidence<input name="evidence" required minLength={5} maxLength={500} placeholder="Meta post insights checked today" /></label><p className="income-note">Leave unavailable values blank. Only report values actually shown by Meta.</p><button disabled={busy}>Save measurements</button></form></details>
    <details><summary>Reconcile an uncertain publish</summary><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void action({ action: "reconcile", postId: f.get("post"), externalId: f.get("externalId") }); }}><label>Attempt<select name="post" required>{data.posts.filter(p => ["sending", "uncertain"].includes(p.status)).map(p => <option value={p.id} key={p.id}>{p.headline}</option>)}</select></label><label>Facebook post ID<input name="externalId" required placeholder="1156652300855210_…" /></label><p>We verify the Page and exact copy against Meta before marking this published.</p><button disabled={busy}>Verify existing post</button></form></details></section>
  </main>;
}
