// AUTOGENERATED by scripts/gen-wedding-photos-gemini.ts — do not edit by hand.
// Gallery photos generated via Gemini Imagen; about-section portrait is the
// real cropped brochure photo of Emily & Trevor (preserved verbatim).

export type WeddingPhoto = {
  id: string;
  width: number;
  height: number;
  ratio: number;
  blurDataURL: string;
  alt: string;
  span?: 1 | 2;
  src: string;
};

export const PHOTOS: WeddingPhoto[] = [
{
    "id": "emily-trevor-portrait",
    "width": 1424,
    "height": 1215,
    "ratio": 1.172,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAwAgCdASoMAAoAA4BaJZQCdAELZTQWCw7iAAD+eJoQCem/W7/LWf3mcgzZv2RL//UXltTLWTkcyDTwNhpOzExFgsZq/ZVAAAA=",
    "alt": "Emily and Trevor Hawk at the sweetheart table \u2014 \"found the one whom my soul loves\"",
    "span": 1,
    "src": "/e-and-t/photos/extracted/emily-trevor-portrait"
  },
  {
    "id": "ceremony-arch-sunset",
    "width": 1408,
    "height": 768,
    "ratio": 1.8333,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAAcAA4BaJZgCdAECpTG6jgAA/uGqVfwCY1hrlg25r0Qs/mSQJ3W7dtDWUbfxMOwMci+LNZBOEYw7J/i4MAAA",
    "alt": "Wooden ceremony arch draped with sage greenery and blush roses at sunset, no people",
    "span": 2,
    "src": "/e-and-t/photos/generated/ceremony-arch-sunset"
  },
  {
    "id": "sweetheart-table-candles",
    "width": 1408,
    "height": 768,
    "ratio": 1.8333,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoMAAcAA4BaJQBOgCFqlG3XfgAA/q1EcJeK+8mErpVySaDKnL+vb592VhMLS/kF1bpu4yq/iEcwvLDsU5w9sNGwXuUBiP46wAA=",
    "alt": "Sweetheart table set with cream candles in brass holders and eucalyptus garland",
    "span": 1,
    "src": "/e-and-t/photos/generated/sweetheart-table-candles"
  },
  {
    "id": "bridal-bouquet-rings",
    "width": 1408,
    "height": 768,
    "ratio": 1.8333,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoMAAcAA4BaJQBOgB9lJfqLwAD+6FqNFiaZgtTeOtkBfZBqHelgTuxFWc2Taw4qXWFO48256Tz741S/IHYtdak+AAA=",
    "alt": "Bride's bouquet of cream roses and eucalyptus resting beside two gold wedding bands",
    "span": 1,
    "src": "/e-and-t/photos/generated/bridal-bouquet-rings"
  },
  {
    "id": "cross-altar-candles",
    "width": 1408,
    "height": 768,
    "ratio": 1.8333,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoMAAcAA4BaJZACdAELKUrXAAD+rZHahicpXGf0pDJu23GmHYCK9BQZxHos0AjwLim9EbJ60Q1Ih/fBskHJuoormAAAAA==",
    "alt": "Wooden cross altar with cream candles and soft greenery at a quiet outdoor ceremony",
    "span": 1,
    "src": "/e-and-t/photos/generated/cross-altar-candles"
  },
  {
    "id": "first-dance-string-lights",
    "width": 1376,
    "height": 768,
    "ratio": 1.7917,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoMAAcAA4BaJQBOgBuhggQAAP7qTPxF284TsHPj/OgypqdRAJ1L1e+vj/Kfx+AJ0u0iVvyME13/x98sMAIGdT+PATd10AAA",
    "alt": "Bride and groom slow dancing beneath warm Edison-bulb string lights at an outdoor reception",
    "span": 2,
    "src": "/e-and-t/photos/generated/first-dance-string-lights"
  },
  {
    "id": "reception-toast",
    "width": 1408,
    "height": 768,
    "ratio": 1.8333,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAAcAA4BaJQBOgCLY9t+Tq/AA/t31LrylGt/kHUTtha+zi5qNzHg+M2phiJ/ciT+JjiBc7D6yr9/Gry6wiAAA",
    "alt": "Guests raising champagne glasses in a toast under warm string lights at an outdoor reception",
    "span": 1,
    "src": "/e-and-t/photos/generated/reception-toast"
  }
];
