import assert from 'node:assert/strict';
import { createOwnerSession } from './helpers/owner-session.mjs';
import { chromium, request } from 'playwright';
import { PrismaClient } from '@prisma/client';
const base = process.env.DISCOVERY_TEST_URL || 'http://127.0.0.1:3024';
if (!['127.0.0.1', 'localhost'].includes(new URL(base).hostname)) throw new Error('This test only submits to a local server.');
const db = new PrismaClient({ datasources: { db: { url: 'postgresql://postgres@127.0.0.1:55450/tolley_discovery_release_test' } } });
const api = await request.newContext({ baseURL: base, timeout: 120000, extraHTTPHeaders: { "x-forwarded-for": `127.0.5.${Math.floor(Math.random() * 200) + 1}` } });
const stamp = Date.now().toString();
let browser, owner;
try {
  assert.equal((await api.get('/api/hq/discovery')).status(), 401);
  assert.equal((await api.post('/api/hq/discovery', { data: { operation: 'lead' } })).status(), 401);
  owner = await createOwnerSession(db, base);
  const admin = await request.newContext({ baseURL: base, timeout: 120000, extraHTTPHeaders: { Cookie: owner.cookie } });
  const create = await admin.post('/api/hq/discovery', { data: { operation: 'lead', name: `Discovery test ${stamp}`, offer: 'cleanouts', reportedSource: 'ChatGPT' } });
  assert.equal(create.status(), 200, await create.text());
  const root = (await create.json()).leadId;
  const childResp = await admin.post('/api/hq/discovery', { data: { operation: 'lead', name: `Discovery related ${stamp}`, offer: 'homes', referralRootId: root } });
  assert.equal(childResp.status(), 200);
  const child = (await childResp.json()).leadId;
  assert.equal((await admin.post('/api/hq/discovery', { data: { operation: 'outcome', leadId: root, stage: 'estimated' } })).status(), 200);
  const revenue = { operation: 'revenue', leadId: root, receiptKey: `discovery-test-${stamp}`, amountCents: 25000, collectedAt: new Date().toISOString() };
  assert.equal((await admin.post('/api/hq/discovery', { data: revenue })).status(), 200);
  assert.equal((await admin.post('/api/hq/discovery', { data: revenue })).status(), 409);
  const report = await (await admin.get('/api/hq/discovery')).json();
  assert.equal(report.groups.find(g => g.offering === 'homes' && g.source === 'chatgpt').booked, 0);
  assert.ok(report.collectedCents >= 25000);
  const action = await db.leadAction.create({ data: { receiptToken: `invite-${stamp}`, subsite: 'animate', action: 'invite-request', name: `Studio ${stamp}`, attribution: { reportedSource: 'ChatGPT' }, status: 'won' } });
  const before = await (await admin.get('/api/hq/discovery')).json();
  const beforeCount = before.groups.find(g => g.offering === 'animate' && g.source === 'chatgpt').inquiries;
  assert.equal((await admin.post('/api/hq/discovery', { data: { operation: 'outcome', leadId: `action:${action.id}`, stage: 'qualified' } })).status(), 200);
  const after = await (await admin.get('/api/hq/discovery')).json();
  assert.equal(after.groups.find(g => g.offering === 'animate' && g.source === 'chatgpt').inquiries, beforeCount, 'Materializing an action doubled inquiries');
  assert.equal(after.groups.find(g => g.offering === 'animate' && g.source === 'chatgpt').booked, 0, 'Invite approval was counted as a booking');
  const invalid = await api.post('/api/discovery/inquiry', { data: { offering: 'billing', name: 'Example', contact: 'test@example.invalid' } });
  assert.equal(invalid.status(), 400);
  const inquiry = await api.post('/api/discovery/inquiry', { data: { offering: 'wd', name: `Public inquiry ${stamp}`, contact: 'test@example.invalid', attribution: { referrerHost: 'chatgpt.com', reportedSource: 'A friend', campaignSource: 'test-campaign', landingPath: '/wd' } } });
  assert.equal(inquiry.status(), 200, await inquiry.text());
  const stored = await db.growthLead.findUnique({ where: { id: (await inquiry.json()).leadId } });
  assert.equal(stored.attribution.browserSource, 'chatgpt');
  assert.equal(stored.attribution.reportedSource, 'A friend');
  assert.equal(stored.attribution.campaignSource, 'test-campaign');
  const old = await db.growthLead.create({ data: { name: `Legacy ${stamp}`, offer: 'site', source: 'serpapi' } });
  assert.equal(old.attribution, null);
  browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
  await context.route('**/*', route => new URL(route.request().url()).origin === new URL(base).origin ? route.continue() : route.abort());
  const page = await context.newPage();
  page.setDefaultTimeout(120000);
  page.on('pageerror', e => console.error('Browser error:', e.message));
  const views = [];
  page.on('request', req => { if (req.url().endsWith('/api/analytics') && req.method() === 'POST') { const b = req.postDataJSON(); if (b.type === 'view') views.push(b); } });
  await page.goto(base + '/cleanouts', { referer: 'https://chatgpt.com/', waitUntil: 'domcontentloaded', timeout: 120000 });
  await page.locator('#service-details').waitFor();
  await page.getByRole('heading', { name: /Estate & rental cleanouts/ }).waitFor();
  await page.waitForFunction(() => !!sessionStorage.getItem("tolley.discovery.v1"), null, { timeout: 60000 });
  await page.waitForTimeout(1000);
  assert.equal(views.filter(v => v.site === 'cleanouts').length, 1, 'Duplicate cleanouts pageview');
  assert.equal(views.find(v => v.site === 'cleanouts').attribution.browserSource, 'chatgpt');
  assert.ok(await page.locator('a[href="tel:+19132833826"]').count());
  assert.ok(await page.locator('#service-details').isVisible());
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1), false, 'Mobile overflow');
  await page.screenshot({ path: '/tmp/tolley-discovery-cleanouts-mobile.png', fullPage: true });
  await Promise.all([
    page.waitForRequest(req => req.url().endsWith('/api/analytics') && req.method() === 'POST' && req.postDataJSON().site === 'homes'),
    page.locator('#service-details a[href="/homes"]').click(),
  ]);
  await page.waitForURL('**/homes');
  await page.locator('#service-details').waitFor();
  assert.equal(views.find(v => v.site === 'homes').attribution.browserSource, 'chatgpt', 'Lost referral on internal navigation');
  const nojs = await browser.newContext({ javaScriptEnabled: false });
  const plain = await nojs.newPage();
  await plain.goto(base + '/wd', { timeout: 120000 });
  assert.ok((await plain.locator('#service-details').innerText()).includes('42'));
  const ld = await api.get('/llms.txt');
  assert.equal(ld.status(), 200); assert.ok((await ld.text()).includes('FIRMAN T07571'));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(base + '/services', { timeout: 120000 });
  assert.ok(await page.locator('a[href="/animate"]').count());
  await page.screenshot({ path: '/tmp/tolley-discovery-directory.png', fullPage: true });
  await nojs.close(); await context.close(); await admin.dispose();
  console.log(JSON.stringify({ ok: true, checks: ['owner-only report', 'manual phone lead', 'related opportunity', 'stages', 'receipt deduplication', 'public inquiry storage', 'legacy nullable compatibility', 'mobile cleanouts', 'deduplicated pageview', 'cross-page attribution', 'no-JavaScript facts', 'generated llms', 'desktop directory'], root, child }));
} finally { await browser?.close(); await api.dispose(); await owner?.cleanup(); await db.$disconnect(); }
