import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { prisma } from "../lib/prisma";
import { createBatch, dispatchQueued, jobAction, recoverJob, refreshJobs, saveCommission, saveProduct, verifyAccount } from "../lib/shop-video/store";

const db=new URL(process.env.DATABASE_URL||"http://missing");
if(db.hostname!=="127.0.0.1"||db.port!=="55449"||db.pathname!=="/tolley_shop_video_test")throw new Error("Use the isolated Shop Video test database on port 55449");
const connections=async()=>[{externalAccountId:"test-shop",username:"ourshop",displayName:"Our shop"}];
const cloud={workerHealth:async()=>({ready:true,fal:true,version:"store-display-v1"}),connectedTikTokAccounts:connections};
const ready={status:"ready" as const,size:1000,sha256:"a".repeat(64),duration:8,width:1080,height:1920,providerEstimateCents:5,actualCostCents:5,receipts:[{model:"test",request_id:"receipt-1",estimatedCents:5}]};
const review={action:"approve",productMatches:true,claimsAccurate:true,rightsConfirmed:true,precheckPassed:true};
const handoff={action:"handoff",disclosureConfirmed:true,commercialAudioConfirmed:true,productLinkConfirmed:true};
async function main(){
  await prisma.shopVideoCommission.deleteMany();await prisma.shopVideoJob.deleteMany();await prisma.shopVideoBatch.deleteMany();await prisma.shopVideoProduct.deleteMany();await prisma.shopVideoAccount.deleteMany();
  const p=await saveProduct({title:"Test case",productId:"123456789012345",productUrl:"https://www.tiktok.com/view/product/123456789012345",imageUrl:"https://test.public.blob.vercel-storage.com/a.png",seller:"Test seller",variant:"Black",priceCents:2000,commissionBps:1000,rightsConfirmed:true,authenticityConfirmed:true});
  const account=await verifyAccount({externalAccountId:"test-shop",dailyQuota:1,weeklyQuota:2,affiliateAccessConfirmed:true,quotaConfirmed:true},connections);
  const input={requestKey:randomUUID(),accountId:account.id,productIds:[p.id],provider:"fal",format:"boomerang",scene:"original",overlay:"Test display",maxSpendCents:5};
  await assert.rejects(()=>createBatch({...input,requestKey:randomUUID(),format:"hybrid"},cloud),/real demonstration/);
  await assert.rejects(()=>createBatch({...input,requestKey:randomUUID(),provider:"modal"},cloud),/spending limit/);
  const batches=await Promise.all([createBatch(input,cloud),createBatch(input,cloud)]);assert.equal(batches[0].id,batches[1].id);
  await assert.rejects(()=>createBatch({...input,overlay:"Different paid request"},cloud),/different settings/);
  let spawns=0;const submit=async()=>{spawns++;await new Promise(r=>setTimeout(r,30));return "fc-test";};
  await Promise.all([dispatchQueued(batches[0].id,submit),dispatchQueued(batches[0].id,submit)]);assert.equal(spawns,1);
  await refreshJobs(async()=>ready,submit);
  const j=await prisma.shopVideoJob.findFirstOrThrow({where:{batchId:batches[0].id}});assert.equal(j.status,"ready");assert.equal(j.actualCostCents,null,"an estimate must never become a confirmed charge");
  await assert.rejects(()=>jobAction(j.id,{...review,precheckPassed:false},connections),/pre-check/);
  await jobAction(j.id,review,connections);
  const b2=await createBatch({...input,requestKey:randomUUID()},cloud);await dispatchQueued(b2.id,submit);await refreshJobs(async()=>ready,submit);
  const j2=await prisma.shopVideoJob.findFirstOrThrow({where:{batchId:b2.id}});await jobAction(j2.id,review,connections);
  const attempts=await Promise.allSettled([jobAction(j.id,handoff,connections),jobAction(j2.id,handoff,connections)]);
  assert.equal(attempts.filter(r=>r.status==="fulfilled").length,1,"concurrent handoffs cannot exceed daily quota");
  const posting=await prisma.shopVideoJob.findFirstOrThrow({where:{status:"handoff"}});
  await assert.rejects(()=>jobAction(posting.id,{action:"published",url:"https://www.tiktok.com/@TurnerSells/video/123456789012345"},connections),/selected TikTok account/);
  await jobAction(posting.id,{action:"published",url:"https://www.tiktok.com/@ourshop/video/123456789012345"},connections);
  await assert.rejects(()=>jobAction(posting.id,review,connections),/completed video/);
  const order={externalId:"order-line-1",jobId:posting.id,amountCents:200,status:"pending",evidence:"test order export"};
  await Promise.all([saveCommission(order),saveCommission(order)]);assert.equal(await prisma.shopVideoCommission.count(),1);
  await saveCommission({...order,status:"settled"});await assert.rejects(()=>saveCommission(order),/older order/);
  await saveCommission({...order,status:"reversed"});await assert.rejects(()=>saveCommission({...order,status:"settled"}),/older order/);
  const b3=await createBatch({...input,requestKey:randomUUID()},cloud);let ambiguous=0;
  const lost=async()=>{ambiguous++;throw new Error("response lost after paid spawn");};
  await dispatchQueued(b3.id,lost);await dispatchQueued(b3.id,lost);assert.equal(ambiguous,1);
  const held=await prisma.shopVideoJob.findFirstOrThrow({where:{batchId:b3.id}});assert.equal(held.status,"held");
  await assert.rejects(()=>recoverJob(held.id,async()=>null),/No completed result/);
  await recoverJob(held.id,async()=>({...ready,width:480}));assert.equal((await prisma.shopVideoJob.findUniqueOrThrow({where:{id:held.id}})).status,"held");
  await recoverJob(held.id,async()=>ready);assert.equal((await prisma.shopVideoJob.findUniqueOrThrow({where:{id:held.id}})).status,"ready");assert.equal(ambiguous,1);
  await prisma.shopVideoAccount.update({where:{id:account.id},data:{verifiedAt:new Date(Date.now()-8*86400000)}});
  await assert.rejects(()=>createBatch({...input,requestKey:randomUUID()},cloud),/affiliate access/);
  console.log("Shop Video workflow passed: real database races, one paid dispatch, quota locking, review, receipts, commissions, and recovery");
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>prisma.$disconnect());
