"use client";
import { useState } from "react";
import { resaleMath } from "@/lib/growth/core";
export default function Calculators() {
  const [values, setValues] = useState([40, 15, 0, 0, 0, 10]);
  const [lotCost,setLotCost] = useState(0), [lotUnits,setLotUnits] = useState(1);
  const result = resaleMath(values[0],values[1],values[2],values[3],values[4],values[5]);
  const labels = ["Expected resale price ($)","Acquisition cost incl. shipping/tax ($)","Your selling fee estimate (%)","Fixed selling costs per sale ($)","Packing, shipping, returns & labor allowance ($)","Desired profit ($)"];
  const money = (n: number) => n.toLocaleString("en-US", { style: "currency", currency: "USD" });
  return <section className="rounded-xl border p-5 space-y-4"><h2 className="text-2xl">Resale planning tools</h2><p>Enter estimates for one item. Include every cost you expect to pay. Use the separate lot calculator below for bulk purchases.</p><div className="grid gap-4 sm:grid-cols-2">{labels.map((l,i) => <label key={l}>{l}<input className="block w-full rounded border p-2 bg-transparent" type="number" min={0} step={.01} value={Number.isFinite(values[i]) ? values[i] : ""} onChange={e => setValues(values.map((v,j) => j === i ? e.target.value === "" ? NaN : Number(e.target.value) : v))}/></label>)}</div><div aria-live="polite">{result ? <><p>Estimated profit: {money(result.profit)}</p><p>Maximum acquisition cost for your desired profit: {money(result.maximumBuy)}</p><p>Break-even resale price: {money(result.breakEvenSale)}</p></> : <p>Enter valid nonnegative amounts and fees below 100%.</p>}</div><h3 className="text-xl">Lot cost per item</h3><label className="block">Total lot acquisition cost ($)<input className="block w-full rounded border p-2 bg-transparent" type="number" min="0" step="0.01" value={lotCost} onChange={e=>setLotCost(Number(e.target.value))}/></label><label className="block">Number of items<input className="block w-full rounded border p-2 bg-transparent" type="number" min="1" step="1" value={lotUnits} onChange={e=>setLotUnits(Number(e.target.value))}/></label><p aria-live="polite">{lotCost>=0 && Number.isFinite(lotCost) && Number.isInteger(lotUnits) && lotUnits>0 ? `Cost per item: ${money(lotCost/lotUnits)}` : "Enter a valid cost and a positive whole number of items."}</p></section>;
}
