"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { contribution, ledgerSchema } from "@/lib/live/core";
import type { Ledger } from "@/lib/live/core";
type Show = { id: string; title: string; startsAt: string; ledger: unknown };
type Clip = { id: string; title: string; status: string; review: { reason?: string }; publications: { platform: string; status: string; url?: string; error?: string }[] };
type Data = { settings: { publishingPaused: boolean; bindings: Record<string,{ accountId: string; label: string }> } | null; shows: Show[]; clips: Clip[]; clicks: { label: string; _count: number }[] };
const money = (n: number) => n.toLocaleString("en-US", { style: "currency", currency: "USD" });
export default function Growth() {
  const [data,setData] = useState<Data|null>(null); const [error,setError] = useState(""); const [busy,setBusy] = useState(false);
  async function load() { const r = await fetch("/api/live/manage", { cache: "no-store" }); if (!r.ok) throw new Error("Sign in with your owner account to load show management."); setData(await r.json()); }
  useEffect(() => { void load().catch(e => setError(e.message)); }, []);
  async function save(body: unknown) { setBusy(true); setError(""); try { const r = await fetch("/api/live/manage", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!r.ok) throw new Error((await r.json()).error); await load(); return true; } catch(e) { setError(e instanceof Error ? e.message : "Save failed"); return false; } finally { setBusy(false); } }
  const spent = (data?.shows || []).reduce((sum,s) => { const l=ledgerSchema.safeParse(s.ledger);return sum+(l.success?l.data.ads:0); },0);
  return <main style={{ maxWidth: 950, margin: "auto", padding: 24, background: "#0b1220", color: "#eef", minHeight: "100vh" }}><style>{`.growth-form{display:grid;gap:12px;margin:20px 0}.growth-form input,.growth-form select{background:#17243a;color:#fff;border:1px solid #65758b;border-radius:6px;padding:10px;width:100%}.growth-form label{font-size:13px;display:grid;gap:6px}.growth-form button,.growth-btn{background:#cee976;color:#182118;border:0;border-radius:6px;padding:10px 14px;cursor:pointer}.growth-box{border:1px solid #384353;border-radius:8px;padding:18px;margin:16px 0}.growth-costs{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:12px}button:disabled{opacity:.5}`}</style>
    <Link href="/stream">← Control room</Link> · <Link href="/live">Public live page ↗</Link><h1 style={{fontSize:30,marginTop:24}}>Treasure Hauls · growth</h1><p>Daily shows, 1–3 hours. All public show times display in America/Chicago.</p>{error && <p role="alert" style={{color:"#ffb4a5"}}>{error}</p>}
    <section className="growth-box"><h2>Schedule the next haul</h2><p>Create the show in Whatnot first, then add its link here. This publishes its schedule to /live.</p><form className="growth-form" onSubmit={async e => {e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(await save({action:"show",show:{title:f.get("title"),category:f.get("category"),startsAt:new Date(String(f.get("startsAt"))).toISOString(),durationMin:Number(f.get("durationMin")),whatnotUrl:f.get("whatnotUrl")}})) form.reset();}}><label>Show title<input name="title" required minLength={3} maxLength={120} placeholder="Tested gadgets & garage finds"/></label><label>Theme<select name="category"><option>Electronics</option><option>Home &amp; Garden</option><option>Estate / mixed finds</option></select></label><label>Start time (your device’s local timezone)<input type="datetime-local" name="startsAt" required/></label><label>Length<select name="durationMin"><option value="60">1 hour</option><option value="120">2 hours</option><option value="180">3 hours</option></select></label><label>Whatnot show URL<input name="whatnotUrl" type="url" required placeholder="https://www.whatnot.com/live/…"/></label><button disabled={busy}>Add to public schedule</button></form></section>
    <section className="growth-box"><h2>Automatic clips</h2><p>{data?.settings?.publishingPaused === false ? "Publishing enabled · up to 2 clips per platform per day." : "Publishing paused."} Only clips passing the content checks are eligible. Unknown publish results are held for reconciliation, never blindly retried.</p><p>Accounts: {Object.entries(data?.settings?.bindings || {}).map(([p,b]) => `${p}: ${b.label}`).join(" · ") || "No verified accounts bound"}</p><button className="growth-btn" disabled={busy || !data} onClick={()=>void save({action:"pause",paused:data?.settings?.publishingPaused === false})}>{data?.settings?.publishingPaused === false ? "Pause publishing" : "Enable publishing"}</button>{data?.clips.map(c=><div className="growth-box" key={c.id}><b>{c.title}</b> · {c.status}<p>{c.review.reason}</p>{c.publications.map(p=><p key={p.platform}>{p.platform}: {p.status} {p.url && <a href={p.url}>View ↗</a>} {p.error}</p>)}<button className="growth-btn" disabled={busy} onClick={()=>void save({action:"hold",id:c.id})}>Hold clip</button></div>)}</section>
    <section className="growth-box"><h2>Promotion experiment · $100 total ceiling</h2><p>Recorded ad spend: {money(spent)} · Remaining: {money(Math.max(0,100-spent))}{spent>100?" · Budget exceeded":""}</p><p>Six matched shows: $0, $10, $0, $20, $10, $20. Keep $40 in reserve. These are total show caps, not hourly budgets. Buying promotions stays in Whatnot.</p><p>Compare contribution per live hour with similar unpaid shows. Attributed sales alone are not incremental profit.</p></section>
    {data?.shows.map(s=><section className="growth-box" key={s.id}><h2>{s.title}</h2><p>{new Date(s.startsAt).toLocaleString("en-US",{timeZone:"America/Chicago"})} Central</p><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className="growth-btn" disabled={busy} onClick={()=>void save({action:"confirm",id:s.id})}>I verified this show is live on Whatnot</button><button className="growth-btn" disabled={busy} onClick={()=>void save({action:"end",id:s.id})}>Mark show ended on public page</button></div><p>These controls update the public listing only. They do not start or stop a stream.</p><LedgerForm show={s} busy={busy} save={save}/></section>)}
    <section className="growth-box"><h2>Whatnot outbound clicks · last 30 days</h2>{data?.clicks.map(c=><p key={c.label}>{c.label}: {c._count}</p>)}<p>Clicks are not verified signups or purchases.</p></section>
  </main>;
}
function LedgerForm({show,busy,save}:{show:Show;busy:boolean;save:(b:unknown)=>Promise<boolean>}) {
  const existing=ledgerSchema.safeParse(show.ledger);const summary=existing.success?contribution(existing.data):null;
  const fields: [keyof Omit<Ledger,"settled">,string][]=[["sales","Gross sales"],["fees","Actual platform fees"],["inventory","Inventory cost"],["fulfillment","Packing / seller shipping / transport"],["refunds","Refund costs"],["ads","Ad spend"],["labor","Labor cost"],["minutes","Live minutes"],["orders","Orders"]];
  return <details><summary style={{cursor:"pointer",marginTop:18}}>Show costs & results</summary>{summary&&<p>{existing.success&&existing.data.settled?"Settled":"Estimated"}: {money(summary.afterAds)} after ads, before labor · {money(summary.afterLabor)} after labor · {money(summary.perHour)}/hour. Break-even extra sales for this ad spend: {summary.breakEvenExtraSales===null?"No positive margin":money(summary.breakEvenExtraSales)}.</p>}<form className="growth-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await save({action:"ledger",id:show.id,ledger:{...Object.fromEntries(fields.map(([k])=>[k,Number(f.get(k))])),settled:f.get("settled")==="on"}});}}><div className="growth-costs">{fields.map(([k,label])=><label key={k}>{label}<input type="number" name={k} step={k==="orders"?"1":"0.01"} min={k==="minutes"?1:0} required defaultValue={existing.success?existing.data[k]:k==="inventory"?0:undefined}/></label>)}</div><label><span><input style={{width:"auto"}} type="checkbox" name="settled" defaultChecked={existing.success&&existing.data.settled}/> Reconciled against seller statement</span></label><button disabled={busy}>Save show results</button></form></details>;
}
