#!/usr/bin/env bash
# Cloud Agent install phase — idempotent, must terminate.
#
# Prepares the repository for local development:
#   1. Node dependencies (npm ci against the committed lockfile).
#   2. A local PostgreSQL 16 server (the app's only hard runtime dependency).
#   3. A dev .env.local (generated once; never committed).
#   4. Prisma client + schema materialized into the local database.
#
# NOTE on schema sync: the committed migration history is NOT replayable from an
# empty database (migration 20260309_add_dossier_system references a "Listing"
# table that no migration creates — production drifted from the history). For a
# throwaway local dev database we therefore sync with `prisma db push`, which
# materializes prisma/schema.prisma directly. Production still uses migrations.
set -euo pipefail

cd "$(dirname "$0")/.."
REPO_DIR="$(pwd)"

echo "==> [install] Node dependencies"
if [ -f package-lock.json ]; then
  npm ci
else
  npm install
fi

echo "==> [install] Ensure PostgreSQL is installed"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

# Bring the default cluster online for setup (setup-time only; the per-boot
# start lives in .cursor/start.sh). policy-rc.d blocks service auto-start in the
# container, so drive the cluster directly.
echo "==> [install] Start PostgreSQL cluster"
sudo pg_ctlcluster 16 main start 2>/dev/null || true
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done

echo "==> [install] Ensure role 'app' and database 'tagent'"
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='app'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE ROLE app LOGIN PASSWORD 'app';"
sudo -u postgres psql -c "ALTER ROLE app CREATEDB;" >/dev/null
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='tagent'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE DATABASE tagent OWNER app;"

echo "==> [install] Ensure .env.local"
if [ ! -f .env.local ]; then
  cat > .env.local <<EOF
# Local Cloud Agent development environment — generated by .cursor/install.sh.
# Not committed (.env* is gitignored). Replace placeholders with real secrets
# to exercise Stripe / Anthropic / Twilio / email flows.
DATABASE_URL="postgresql://app:app@127.0.0.1:5432/tagent?schema=public"
AUTH_SECRET="$(openssl rand -base64 32)"
AUTH_URL="http://localhost:3000"
NEXTAUTH_URL="http://localhost:3000"
APP_URL="http://localhost:3000"
NODE_ENV="development"
EOF
  echo "    wrote .env.local"
else
  echo "    .env.local already present — leaving untouched"
fi

# Export the generated vars so Prisma sees DATABASE_URL.
set -a
# shellcheck disable=SC1091
. ./.env.local
set +a

echo "==> [install] Prisma generate + schema sync"
npx prisma generate
npx prisma db push --skip-generate --accept-data-loss

echo "==> [install] Done"
