import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const products = [
  // ═══ Chemicals — real Pool360 contractor pricing (2026-03-13) ═══

  // Chlorine Tablets
  {
    sku: "SCU-50-3825",
    name: "3\" All-In-1 Chlorinating Tablets",
    description: "Stabilized trichlor tablets for consistent sanitization. Slow-dissolving for weeks of protection.",
    category: "Chemicals",
    price: 139,
    costPrice: 97.50,
    retailPrice: 189,
    brand: "Pool Mate",
    unit: "bucket",
    size: "25lb",
    featured: true,
    sortOrder: 1,
  },
  {
    sku: "SCU-50-3725",
    name: "3\" Jumbo Sanitizing Chlorinating Tablets",
    description: "Wrapped chlorinating tablets for long-lasting pool sanitization.",
    category: "Chemicals",
    price: 169,
    costPrice: 123.67,
    retailPrice: 219,
    brand: "Pool Basics",
    unit: "bucket",
    size: "25lb",
    sortOrder: 2,
  },

  // Liquid Chlorine / Shock
  {
    sku: "CHP-50-8425",
    name: "12.5% Liquid Pool Shock",
    description: "Professional-grade liquid chlorine shock. Fast-acting, no residue.",
    category: "Chemicals",
    price: 38,
    costPrice: 26.69,
    retailPrice: 54,
    brand: "Champion",
    unit: "case",
    size: "4x1 gal",
    featured: true,
    sortOrder: 3,
  },
  {
    sku: "CHP-50-8413",
    name: "PRO CLOR Liquid Pool Shock",
    description: "Economy liquid chlorine shock treatment. Great for weekly maintenance.",
    category: "Chemicals",
    price: 19,
    costPrice: 13.91,
    retailPrice: 28,
    brand: "Champion",
    unit: "case",
    size: "1 gal",
    sortOrder: 4,
  },

  // Granular Shock (Cal-Hypo)
  {
    sku: "REF-50-1201",
    name: "68% Cal-Hypo Granular Shock",
    description: "Fast-acting calcium hypochlorite granular shock. Kills bacteria and algae overnight.",
    category: "Chemicals",
    price: 129,
    costPrice: 95.03,
    retailPrice: 179,
    brand: "Refresh",
    unit: "pail",
    size: "25lb",
    featured: true,
    sortOrder: 5,
  },
  {
    sku: "AWC-50-5806",
    name: "DryTec Granular Chlorine 68%",
    description: "Individual shock bags — convenient single-dose granular shock treatment.",
    category: "Chemicals",
    price: 5.99,
    costPrice: 4.19,
    retailPrice: 8.99,
    brand: "DryTec",
    unit: "each",
    size: "1lb bag",
    sortOrder: 6,
  },
  {
    sku: "AWC-50-5800",
    name: "DryTec Granular Chlorine 68%",
    description: "Professional cal-hypo granular shock in bulk pail. Economical for regular shocking.",
    category: "Chemicals",
    price: 129,
    costPrice: 94.38,
    retailPrice: 174,
    brand: "DryTec",
    unit: "pail",
    size: "25lb",
    sortOrder: 7,
  },

  // Algaecide
  {
    sku: "RGL-50-2660",
    name: "Algaecide 60",
    description: "Non-foaming 60% poly algaecide. Prevents and treats all types of pool algae.",
    category: "Chemicals",
    price: 29,
    costPrice: 21.86,
    retailPrice: 42,
    brand: "Regal",
    unit: "each",
    size: "1 quart",
    sortOrder: 8,
  },
  {
    sku: "NAT-50-7600",
    name: "Algae Break 90",
    description: "90-day algae prevention and treatment. One application lasts all season.",
    category: "Chemicals",
    price: 32,
    costPrice: 23.69,
    retailPrice: 46,
    brand: "Natural Chemistry",
    unit: "each",
    size: "1 quart",
    featured: true,
    sortOrder: 9,
  },

  // pH / Water Balancers
  {
    sku: "RGL-50-2407",
    name: "pH Minus (pH Decreaser)",
    description: "Granular sodium bisulfate safely lowers pH and total alkalinity.",
    category: "Chemicals",
    price: 14,
    costPrice: 9.82,
    retailPrice: 22,
    brand: "Regal",
    unit: "each",
    size: "6lb",
    sortOrder: 10,
  },
  {
    sku: "RGL-50-2326",
    name: "pH Plus (pH Increaser)",
    description: "Soda ash raises pH quickly. Essential for balanced pool water.",
    category: "Chemicals",
    price: 36,
    costPrice: 27.34,
    retailPrice: 49,
    brand: "Regal",
    unit: "each",
    size: "25lb",
    sortOrder: 11,
  },
  {
    sku: "NUL-50-1707",
    name: "pH Increaser",
    description: "Raises pH quickly without affecting total alkalinity significantly.",
    category: "Chemicals",
    price: 14,
    costPrice: 10.62,
    retailPrice: 22,
    brand: "Nu-Clo",
    unit: "pail",
    size: "5lb",
    sortOrder: 12,
  },

  // Muriatic Acid
  {
    sku: "AAA-50-8602",
    name: "Muriatic Acid (No Deposit)",
    description: "Lowers pH and alkalinity. Also great for cleaning pool tile and concrete.",
    category: "Chemicals",
    price: 10,
    costPrice: 6.76,
    retailPrice: 16,
    brand: "Pool Corp",
    unit: "each",
    size: "1 gal",
    sortOrder: 13,
  },
  {
    sku: "UCS-50-1000",
    name: "Acid Magic Buffered Muriatic Acid",
    description: "90% less fumes than standard muriatic acid. Safer to handle and store.",
    category: "Chemicals",
    price: 15,
    costPrice: 10.86,
    retailPrice: 24,
    brand: "Acid Magic",
    unit: "each",
    size: "1 gal",
    sortOrder: 14,
  },

  // ═══ Equipment — real Pool360 contractor pricing (2026-03-13) ═══

  // Pumps
  {
    sku: "PUR-10-3106",
    name: "IntelliFlo3 VSF Pool Pump 1.5HP",
    description: "Pentair's flagship variable speed pump. Energy Star certified, cuts energy costs up to 80%.",
    category: "Equipment",
    price: 1899,
    costPrice: 1359.43,
    retailPrice: 2399,
    brand: "Pentair",
    unit: "each",
    size: "1.5HP",
    featured: true,
    sortOrder: 20,
  },
  {
    sku: "PAC-10-2002",
    name: "SuperFlo VST Variable Speed Pump 2.2THP",
    description: "Affordable variable speed pump with built-in timer. Quiet operation, easy install.",
    category: "Equipment",
    price: 1849,
    costPrice: 1329.67,
    retailPrice: 2199,
    brand: "Pentair",
    unit: "each",
    size: "2.2THP",
    sortOrder: 21,
  },
  {
    sku: "MOV-10-1003",
    name: "Ai Inverter Pool Pump 2.0HP",
    description: "Smart inverter technology for maximum efficiency. WiFi enabled, ultra-quiet.",
    category: "Equipment",
    price: 1449,
    costPrice: 1049.80,
    retailPrice: 1799,
    brand: "Moov",
    unit: "each",
    size: "2.0HP",
    sortOrder: 22,
  },

  // Filters
  {
    sku: "PAC-05-502",
    name: "Clean and Clear 100 SqFt Cartridge Filter",
    description: "Pentair cartridge filter for pools up to 15,000 gallons. Easy-clean design.",
    category: "Equipment",
    price: 949,
    costPrice: 677.80,
    retailPrice: 1149,
    brand: "Pentair",
    unit: "each",
    size: "100 sq ft",
    sortOrder: 23,
  },
  {
    sku: "PAC-05-305",
    name: "Sand Dollar Top Mount Sand Filter SD80",
    description: "26\" sand filter with multiport valve. Low maintenance, crystal clear water.",
    category: "Equipment",
    price: 829,
    costPrice: 599.51,
    retailPrice: 999,
    brand: "Pentair",
    unit: "each",
    size: "26 inch",
    sortOrder: 24,
  },

  // Salt Chlorine Generators
  {
    sku: "PAC-45-1567",
    name: "IntelliChlor Plus30 Salt Chlorine Generator",
    description: "Complete salt system with power center. Produces chlorine from salt — no more buying chlorine!",
    category: "Equipment",
    price: 1849,
    costPrice: 1320.36,
    retailPrice: 2199,
    brand: "Pentair",
    unit: "each",
    size: "30K gal",
    featured: true,
    sortOrder: 25,
  },
  {
    sku: "GLD-45-0000",
    name: "TurboCell S3 Salt Chlorination Cell 40K gal",
    description: "Hayward replacement salt cell. Self-cleaning, extended life design.",
    category: "Equipment",
    price: 1679,
    costPrice: 1206.28,
    retailPrice: 1999,
    brand: "Hayward",
    unit: "each",
    size: "40K gal",
    sortOrder: 26,
  },

  // Heaters
  {
    sku: "PUR-15-0732",
    name: "MasterTemp Natural Gas Heater 250K BTU",
    description: "Compact, high-performance pool heater. Heats fast, low NOx emissions.",
    category: "Equipment",
    price: 4399,
    costPrice: 3161.62,
    retailPrice: 5199,
    brand: "Pentair",
    unit: "each",
    size: "250K BTU",
    sortOrder: 27,
  },

  // ═══ Accessories — real Pool360 contractor pricing (2026-03-13) ═══
  {
    sku: "TAY-45-1147",
    name: "Taylor Complete Water Test Kit",
    description: "Professional DPD test kit — chlorine, bromine, pH, alkalinity, hardness, CYA. The gold standard.",
    category: "Accessories",
    price: 119,
    costPrice: 85.39,
    retailPrice: 159,
    brand: "Taylor",
    unit: "each",
    size: "2oz reagents",
    featured: true,
    sortOrder: 30,
  },
  {
    sku: "AQC-47-1032",
    name: "AquaChek 7-In-1 Test Strips",
    description: "Quick dip-and-read test strips. Tests chlorine, bromine, pH, alkalinity, hardness, CYA, and more.",
    category: "Accessories",
    price: 44,
    costPrice: 31.84,
    retailPrice: 59,
    brand: "AquaChek",
    unit: "each",
    size: "100 strips",
    sortOrder: 31,
  },
  {
    sku: "AQC-45-1002",
    name: "AquaChek 4-Way Chlorine Test Strips",
    description: "Basic chlorine test strips for quick weekly checks. Easy color-match results.",
    category: "Accessories",
    price: 15,
    costPrice: 10.40,
    retailPrice: 22,
    brand: "AquaChek",
    unit: "each",
    size: "50 strips",
    sortOrder: 32,
  },

  // ═══ Maintenance — real Pool360 contractor pricing (2026-03-13) ═══
  {
    sku: "PSL-40-2013",
    name: "18\" Pool Wall Brush",
    description: "Polybristle wall brush with aluminum handle. Works on all pool surfaces.",
    category: "Maintenance",
    price: 32,
    costPrice: 21.99,
    retailPrice: 44,
    brand: "PoolStyle",
    unit: "each",
    size: "18 inch",
    sortOrder: 40,
  },
  {
    sku: "SPG-40-2006",
    name: "18\" Stainless Steel/Poly Combo Brush",
    description: "Service-grade combo brush with stainless and poly bristles. Tackles tough algae.",
    category: "Maintenance",
    price: 56,
    costPrice: 40.05,
    retailPrice: 74,
    brand: "Super-Pro",
    unit: "each",
    size: "18 inch",
    sortOrder: 41,
  },
  {
    sku: "SPG-40-2014",
    name: "Heavy Duty Deep Net Leaf Rake",
    description: "20\" wide rim mesh leaf rake. Deep bag catches leaves, bugs, and debris.",
    category: "Maintenance",
    price: 52,
    costPrice: 36.38,
    retailPrice: 69,
    brand: "Super-Pro",
    unit: "each",
    size: "20 inch",
    sortOrder: 42,
  },
  {
    sku: "PSL-40-2031",
    name: "Heavy Duty Skimmer Net",
    description: "ABS frame skimmer with durable nylon net. Fits standard telepoles.",
    category: "Maintenance",
    price: 24,
    costPrice: 16.07,
    retailPrice: 32,
    brand: "PoolStyle",
    unit: "each",
    size: "each",
    sortOrder: 43,
  },
  {
    sku: "PSL-40-2066",
    name: "14\" Flex Vacuum Head",
    description: "Flexible vacuum head with metal handle. For vinyl, fiberglass, or concrete pools.",
    category: "Maintenance",
    price: 65,
    costPrice: 46.13,
    retailPrice: 84,
    brand: "PoolStyle",
    unit: "each",
    size: "14 inch",
    sortOrder: 44,
  },
  {
    sku: "PSL-40-9240",
    name: "Vacuum Hose 1.5\" x 40ft",
    description: "Deluxe spiral-wound vacuum hose with swivel cuff ends. UV resistant.",
    category: "Maintenance",
    price: 99,
    costPrice: 72.45,
    retailPrice: 129,
    brand: "PoolStyle",
    unit: "each",
    size: "40ft",
    sortOrder: 45,
  },
  {
    sku: "PSL-40-2045",
    name: "Telescopic Pole 8-16ft",
    description: "Aluminum ribbed telepole with outer lock. Fits brushes, nets, and vacuum heads.",
    category: "Maintenance",
    price: 52,
    costPrice: 36.66,
    retailPrice: 69,
    brand: "PoolStyle",
    unit: "each",
    size: "8-16ft",
    sortOrder: 46,
  },
];

async function main() {
  console.log("Seeding pool products...");

  for (const p of products) {
    await prisma.poolProduct.upsert({
      where: { sku: p.sku },
      update: { ...p },
      create: { ...p, status: "active" },
    });
  }

  const count = await prisma.poolProduct.count();
  console.log(`Done. ${count} pool products in database.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
