export const ACCOMPLISHMENT_LINES = [
  "Converting cold leads into committed clients through trust and clarity.",
  "Separating curiosity from capability with sharp qualification.",
  "Building pricing strategy from data, not optimism.",
  "Engineering a launch plan that creates urgency and demand.",
  "Advising improvements that deliver measurable return, not vanity.",
  "Orchestrating contractors, vendors, and timelines with precision.",
  "Transforming a property’s presentation into a market-ready product.",
  "Producing marketing that attracts the right buyer, not just “views.”",
  "Writing remarks that sell a lifestyle while staying compliant.",
  "Managing showing logistics like an air-traffic controller.",
  "Reading neighborhoods, micro-markets, and buyer psychology in real time.",
  "Guiding buyers away from emotional traps and costly mistakes.",
  "Crafting offers that win on terms, not just price.",
  "Negotiating concessions with composure and leverage.",
  "Identifying red flags before they become deal killers.",
  "Protecting clients through deadline discipline and contingency control.",
  "Translating inspection reports into actionable decisions.",
  "Securing fair repairs or credits without inflaming the room.",
  "Keeping lenders moving and underwriting honest.",
  "Navigating appraisal gaps with creative, legal solutions.",
  "Untangling title defects before they derail closing.",
  "Handling HOA constraints before the buyer discovers them late.",
  "Managing risk with documentation that holds up under scrutiny.",
  "Maintaining momentum when transactions stall.",
  "De-escalating stress while preserving negotiating power.",
  "Running amendments and addenda cleanly, quickly, correctly.",
  "Protecting client privacy while marketing aggressively.",
  "Balancing transparency with strategic restraint.",
  "Aligning agents, inspectors, title, and lenders into one timeline.",
  "Solving problems clients never see—because they never should.",
  "Calibrating expectations to reality without crushing enthusiasm.",
  "Defending value when buyers push and sellers wobble.",
  "Auditing estimates, bids, and scopes of work like a pragmatist.",
  "Recognizing when “cheap” repairs become expensive liabilities.",
  "Designing a showing itinerary that maximizes insight and efficiency.",
  "Distilling complex contracts into plain-English decisions.",
  "Anticipating objections before they surface.",
  "Preventing minor miscommunications from becoming major delays.",
  "Preparing clients so closing feels inevitable, not intimidating.",
  "Catching settlement statement errors before signatures hit paper.",
  "Conducting final walk-throughs with a forensic eye.",
  "Coordinating possession, keys, and utilities without loose ends.",
  "Holding fiduciary duty as the non-negotiable standard.",
  "Protecting time, money, and peace of mind—simultaneously.",
  "Delivering calm leadership when emotions spike.",
  "Creating a system where surprises are rare and solvable.",
  "Turning negotiation into alignment, not conflict.",
  "Building reputation through consistency, not luck.",
  "Converting one closing into a pipeline of referrals.",
  "Rescuing transactions that would quietly die without intervention.",
] as const;
