import assert from 'node:assert/strict';
import { chromium, request } from 'playwright';
import { PrismaClient } from '@prisma/client';
import { createOwnerSession, requireIsolatedServer } from '../helpers/owner-session.mjs';
const base = 'http://localhost:3029'; requireIsolatedServer(base);
const p = new PrismaClient(); const api = await request.newContext({ baseURL: base, timeout:120000 });
let owner, browser;
try {
  assert.equal((await api.get('/api/live/manage')).status(),401);
  assert.equal((await api.get('/api/live/report')).status(),401);
  assert.equal((await api.get('/api/cron/hauls-campaign')).status(),401);
  await p.liveCampaignPost.deleteMany(); await p.liveDeal.deleteMany(); await p.livePublication.deleteMany(); await p.liveClip.deleteMany(); await p.liveShow.deleteMany();
  await p.liveSettings.upsert({where:{id:'treasure-hauls'},create:{campaignPaused:true,bindings:{facebook:{accountId:'test-haul',label:'Test Haul'}}},update:{campaignPaused:true,bindings:{facebook:{accountId:'test-haul',label:'Test Haul'}}}});
  owner = await createOwnerSession(p, base);
  const admin = await request.newContext({baseURL:base,timeout:120000,extraHTTPHeaders:{Cookie:owner.cookie,Origin:base}});
  const save = async body => {const r=await admin.post('/api/live/manage',{data:body});assert.equal(r.status(),200,await r.text());};
  await save({action:'show',show:{title:'Campaign browser test',category:'Electronics',centralDate:'2027-11-08',centralTime:'20:31',durationMin:120,whatnotUrl:'https://www.whatnot.com/live/campaign-test'}});
  const show=await p.liveShow.findFirstOrThrow({where:{title:'Campaign browser test'}});
  assert.equal(show.startsAt.toISOString(),'2027-11-09T02:31:00.000Z');
  assert.equal((await admin.post('/api/live/manage',{data:{action:'confirm',id:show.id}})).status(),400,'draft cannot be marked live');
  await save({action:'schedule_confirm',id:show.id}); await save({action:'pack',id:show.id}); await save({action:'pack',id:show.id});
  assert.equal(await p.liveCampaignPost.count({where:{showId:show.id}}),4,'pack is idempotent');
  const preview=await p.liveCampaignPost.findFirstOrThrow({where:{kind:'preview',showId:show.id}});
  await save({action:'campaign_queue',id:preview.id,caption:preview.caption});
  await save({action:'deal',deal:{showId:show.id,item:'Test kettle',price:12.5,soldAt:'2026-09-20T20:45:00-05:00',evidence:'isolated-fixture.csv row 2',verified:true}});
  browser=await chromium.launch({headless:true,args:['--no-sandbox']});
  const context=await browser.newContext({viewport:{width:390,height:844}}); const page=await context.newPage(); page.setDefaultTimeout(120000); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/live?utm_source=browser_test&utm_campaign=launch',{waitUntil:'networkidle'});
  await page.getByRole('heading',{name:/Come for the show/}).waitFor();
  await page.getByText('Test kettle',{exact:true}).waitFor(); await page.getByText('$12.50',{exact:true}).waitFor();
  assert.equal(await page.getByText('LIVE NOW',{exact:false}).count(),0);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:'/tmp/hauls-mobile.png',fullPage:true});
  const referral=await api.get('/go/whatnot?utm_source=test',{maxRedirects:0});assert.equal(referral.headers().location,'https://www.whatnot.com/invite/treasure_hauls');
  const direct=await api.get('/go/show?show='+show.id,{maxRedirects:0});assert.equal(direct.headers().location,show.whatnotUrl);
  const poster=await api.get('/live/poster?show='+show.id);assert.equal(poster.status(),200);assert.match(poster.headers()['content-type'],/image\/png/);
  await save({action:'confirm',id:show.id});
  await page.reload({waitUntil:'networkidle'});await page.getByRole('link',{name:'We’re live — come hang ↗'}).waitFor();
  await save({action:'end',id:show.id});await page.reload({waitUntil:'networkidle'});assert.equal(await page.getByRole('link',{name:'We’re live — come hang ↗'}).count(),0);
  const second=await p.liveShow.create({data:{title:'Cancel test',category:'Electronics',startsAt:new Date('2027-11-10T02:31:00Z'),durationMin:120,whatnotUrl:'https://www.whatnot.com/live/cancel-test',status:'confirmed'}});
  await save({action:'pack',id:second.id});await save({action:'cancel_show',id:second.id});
  assert.equal(await p.liveCampaignPost.count({where:{showId:second.id,status:'canceled'}}),4);
  const canceled=await api.get('/go/show?show='+second.id,{maxRedirects:0});assert.equal(canceled.headers().location,'https://www.whatnot.com/user/treasure_hauls');
  await context.addCookies(owner.cookie.split('; ').map(pair=>{const i=pair.indexOf('=');return {name:pair.slice(0,i),value:pair.slice(i+1),url:base};}));
  await page.goto(base+'/stream/growth',{waitUntil:'networkidle'});await page.getByRole('heading',{name:'The 8:31 campaign'}).waitFor();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/hauls-growth-mobile.png',fullPage:true});
  const report=await admin.get('/api/live/report');assert.equal(report.status(),200);assert.match(await report.text(),/Clicks are not purchases/);
  assert.deepEqual(errors,[]);
  console.log('PASS: owner credentials/MFA, protected endpoints, draft/confirmed/live/end/cancel, Central schedule, idempotent pack, verified deals, redirects, artwork, mobile public/owner pages, report');
} finally { await browser?.close();await owner?.cleanup();await api.dispose();await p.$disconnect(); }
