import assert from "node:assert/strict";
import { chromium } from "playwright";
import { encode } from "next-auth/jwt";
import { prisma } from "../../lib/prisma";
import { enrollmentKey, signMfaProof } from "../../lib/auth/mfa-proof";

async function main() {
  assert.equal(process.env.DATABASE_URL, "postgresql://postgres@127.0.0.1:55438/tolley_live_growth_test");
  const base = process.env.STREAM_TEST_URL || "http://127.0.0.1:3054";
  const email = "stream-handoff@tolley.invalid";
  const user = await prisma.user.upsert({ where: { email }, create: { email }, update: {} });
  const mfa = await prisma.userMfa.upsert({ where: { userId: user.id }, create: { userId: user.id, verified: true, totpSecret: "test-only" }, update: { verified: true } });
  const session = "stream-guide-test", now = Math.floor(Date.now() / 1000);
  const jwt = await encode({ secret: process.env.AUTH_SECRET!, salt: "authjs.session-token", token: { sub: user.id, email, authSessionId: session, authAt: now, sv: user.sessionVersion, svAt: now }, maxAge: 3600 });
  const browser = await chromium.launch({ headless: true, args: ["--no-sandbox"] });
  try {
    const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
    const page = await context.newPage();
    page.setDefaultTimeout(240000);
    const errors: string[] = [];
    page.on("pageerror", e => errors.push(e.message));
    await page.goto(base + "/stream/guide", { waitUntil: "domcontentloaded", timeout: 240000 });
    assert.match(page.url(), /\/login/);
    assert.equal(await page.getByRole("heading", { name: "Streaming operator guide", exact: true }).count(), 0);
    await context.addCookies([{ name: "authjs.session-token", value: jwt, domain: "127.0.0.1", path: "/" }]);
    await page.goto(base + "/stream/guide", { waitUntil: "domcontentloaded", timeout: 240000 });
    assert.match(page.url(), /\/login|\/mfa/);
    await context.addCookies([{ name: "tolley_mfa", value: signMfaProof(user.id, session, enrollmentKey(mfa)), domain: "127.0.0.1", path: "/" }]);
    await page.goto(base + "/stream/guide", { waitUntil: "domcontentloaded", timeout: 240000 });
    await page.getByRole("heading", { name: "Streaming operator guide", exact: true }).waitFor();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.screenshot({ path: "/tmp/stream-guide-mobile.png", fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.screenshot({ path: "/tmp/stream-guide-desktop.png", fullPage: true });

    const facebook = { verified: true, pageId: "1156652300855210", pageName: "Ruthann’s Treasure Haul", videoId: "123456", title: "Test preview", phase: "UNPUBLISHED", liveNow: false, checkedAt: Date.now()/1000, error: "" };
    const status = { facebook, armed: false, privacy: false, liveSinceS: 0, camera: { connected: false, kbps: 0, sinceS: 0, goneS: 0 }, obs: { connected: true, scene: "Ending", streaming: false, programReady: false, lastError: "" }, mediamtx: { ok: true }, destinations: { facebook: { enabled: false, configured: true, running: false, uptimeS: 0 }, youtube: { enabled: false, configured: true, running: false, uptimeS: 0 }, tiktok: { enabled: false, configured: false, running: false, uptimeS: 0 } }, cameras: [] as { slot: number; label: string; connected: boolean; kbps: number; onAir: boolean; audio: boolean; audioLive: boolean }[], limits: { camGoneEndMin: 15, maxStreamMin: 480, brbAfterS: 5 }, ingest: { url: "test", keyTail: "test" }, studio: { online: true, ageS: 0, studioRunning: false, obsRunning: true, host: "test" }, events: [] };
    page.setDefaultTimeout(30000);
    const commands: { path: string; body: unknown }[] = [];
    let chatRequests = 0;
    await page.route("**/api/stream/**", async route => {
      const request = route.request(), path = new URL(request.url()).pathname;
      if (path.includes("/chat")) chatRequests++;
      if (request.method() !== "GET") {
        const body = request.postDataJSON(); commands.push({ path, body });
        if (path.endsWith("/go-live")) status.armed = true;
        if (path.endsWith("/facebook/golive")) Object.assign(facebook, { goLive: "pending" });
        if (path.endsWith("/facebook/end")) Object.assign(facebook, { liveNow: false, phase: "VOD", goLive: "" });
        if (path.endsWith("/camera")) status.cameras.forEach(c => c.onAir = c.slot === body.slot);
        if (path.endsWith("/destinations")) Object.assign(status.destinations.youtube, { enabled: body.youtube });
      }
      facebook.checkedAt = Date.now()/1000;
      await route.fulfill(path.includes("/thumb/") ? { status: 404 } : { json: status });
    });
    await page.route("**/api/stream-lineup", route => route.fulfill({ json: { active: { slug: "test-show", name: "Test", currentIndex: 3, total: 12, currentTitle: "Samsung S3 Series 27 Inch 100Hz FHD LED Monitor" } } }));
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(base + "/stream", { waitUntil: "domcontentloaded", timeout: 240000 });
    await page.getByRole("heading", { name: "House idle", exact: true }).waitFor();
    assert.equal(await page.getByRole("heading", { name: "📡 Stream" }).count(), 0);
    const arm = page.getByRole("button", { name: "▶ Arm house", exact: true });
    assert.ok((await arm.boundingBox())!.y < 180, "Arm house must be at the top");
    await page.getByText("1 · Arm the house", { exact: true }).waitFor();
    assert.equal(await page.getByRole("button", { name: /GO LIVE on Facebook/ }).count(), 0);
    assert.equal(await page.getByText("OBS", { exact: true }).count(), 0);
    assert.equal(await page.getByText("NAS recording", { exact: true }).count(), 0);
    await page.getByText(/Now selling:.*Samsung/).waitFor();
    assert.equal(await page.getByRole("link", { name: "Show Assistant", exact: true }).getAttribute("href"), "/stream/assistant");
    assert.equal(await page.getByRole("link", { name: /Whatnot product slideshow/ }).count(), 0);
    assert.equal(commands.length, 0, "Opening the page must not arm or publish");
    const tools = page.getByLabel("Help and tools");
    await tools.hover();
    await page.getByRole("link", { name: "Schedule, clips & profit →" }).waitFor({ state: "visible" });
    await page.getByRole("link", { name: /Product display/ }).waitFor({ state: "visible" });
    await page.mouse.move(0, 0);
    await page.getByRole("link", { name: /Product display/ }).waitFor({ state: "hidden" });
    await tools.focus();
    await page.getByRole("link", { name: "Stream Coach ✦" }).waitFor({ state: "visible" });
    await page.keyboard.press("Escape");
    await page.getByRole("link", { name: "Stream Coach ✦" }).waitFor({ state: "hidden" });
    await page.screenshot({ path: "/tmp/stream-simple-mobile.png", fullPage: true });
    console.log("Layout and help menu passed; checking arm/camera flow");
    await arm.click();
    assert.deepEqual(commands.at(-1), { path: "/api/stream/go-live", body: { destinations: { youtube: false, tiktok: false, whatnot: false, facebook: false }, studio: false } });
    await page.getByText("2 · Start your camera", { exact: true }).waitFor();
    status.obs.programReady = true;
    status.obs.streaming = true;
    status.camera.connected = true;
    status.cameras.push({ slot: 1, label: "Phone", connected: true, kbps: 4500, onAir: true, audio: true, audioLive: true }, { slot: 2, label: "DJI", connected: true, kbps: 4500, onAir: false, audio: false, audioLive: false });
    await page.getByRole("button", { name: "Picture and sound are good →" }).waitFor();
    assert.equal(await page.getByRole("button", { name: /GO LIVE on Facebook/ }).count(), 0);
    await page.getByRole("button", { name: "Cut to camera 2" }).click();
    assert.deepEqual(commands.at(-1), { path: "/api/stream/camera", body: { slot: 2 } });
    await page.getByRole("button", { name: "Cut to camera 2" }).getByText("ON AIR").waitFor();
    await page.getByRole("button", { name: "YouTube", exact: true }).click();
    assert.deepEqual(commands.at(-1), { path: "/api/stream/destinations", body: { youtube: true } });
    console.log("Arm, camera cut and YouTube passed; checking Facebook publish");
    await page.screenshot({ path: "/tmp/stream-simple-cameras-mobile.png", fullPage: true });
    await page.getByRole("button", { name: "Picture and sound are good →" }).click();
    const publish = page.getByRole("button", { name: /Hold to GO LIVE on Facebook/ });
    await publish.waitFor();
    await page.getByLabel("Facebook show title", { exact: true }).fill("Test house show");
    await publish.click();
    assert.equal(commands.filter(c => c.path.endsWith("/facebook/golive")).length, 0, "A tap must not publish");
    await publish.focus(); await page.keyboard.down("Space"); await page.waitForTimeout(1200); await page.keyboard.up("Space");
    await page.getByText(/Going live on Facebook…/).waitFor();
    assert.deepEqual(commands.at(-1), { path: "/api/stream/facebook/golive", body: { confirm: true, title: "Test house show" } });
    assert.equal(await page.getByText("● Live on Facebook", { exact: true }).count(), 0, "Pending transport must not claim live");
    Object.assign(facebook, { liveNow: true, phase: "LIVE", goLive: "live" });
    status.destinations.facebook.enabled = true; status.destinations.facebook.running = true;
    await page.getByText("● Live on Facebook", { exact: true }).waitFor();
    page.once("dialog", dialog => dialog.accept());
    await page.getByRole("button", { name: "■ End Facebook show", exact: true }).click();
    assert.deepEqual(commands.at(-1), { path: "/api/stream/facebook/end", body: {} });
    status.destinations.facebook.enabled = false; status.destinations.facebook.running = false;
    await page.getByRole("button", { name: "Picture and sound are good →" }).waitFor();
    await page.getByRole("button", { name: "Picture and sound are good →" }).click();
    await publish.waitFor();
    status.obs.programReady = false;
    await page.getByText("2 · Start your camera", { exact: true }).waitFor();
    status.obs.programReady = true;
    await page.getByRole("button", { name: "Picture and sound are good →" }).waitFor();
    assert.equal(await publish.count(), 0, "A feed loss must clear the readiness check");
    await page.getByRole("button", { name: "Picture and sound are good →" }).click();
    console.log("Facebook publish/end and feed-loss gates passed; checking cancellation and manual setup");
    // Losing the page/status while holding must cancel publication.
    const priorPublishes = commands.filter(c => c.path.endsWith("/facebook/golive")).length;
    await publish.focus(); await page.keyboard.down("Space");
    await page.goto(base + "/stream/guide", { waitUntil: "domcontentloaded" });
    await page.keyboard.up("Space"); await page.waitForTimeout(1200);
    assert.equal(commands.filter(c => c.path.endsWith("/facebook/golive")).length, priorPublishes);
    await page.goto(base + "/stream", { waitUntil: "domcontentloaded" });
    await page.getByRole("heading", { name: "Facebook", exact: true }).waitFor();
    await page.getByRole("button", { name: "Picture and sound are good →" }).click();
    await page.getByText("Manual setup & details", { exact: true }).click();
    await page.getByRole("button", { name: "Create Facebook preview", exact: true }).click();
    assert.equal(commands.at(-1)?.path, "/api/stream/facebook/prepare");
    Object.assign(facebook, { phase: "KEYED", ingest: "manual" });
    status.destinations.facebook.enabled = true; status.destinations.facebook.running = true;
    await page.getByText("3 · Go live in Facebook", { exact: true }).waitFor();
    assert.equal(await publish.count(), 0, "An active manual sender must stay in the manual publish path");
    await page.setViewportSize({ width: 1440, height: 1000 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.screenshot({ path: "/tmp/stream-simple-desktop.png", fullPage: true });
    await page.setViewportSize({ width: 320, height: 740 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    assert.equal((await context.request.post(base + "/api/stream/facebook/send", { headers: { Origin: "https://wrong.invalid" }, data: {} })).status(), 403);
    assert.equal((await context.request.post(base + "/api/stream/facebook/send", { headers: { Origin: base }, data: { value: "x".repeat(9000) } })).status(), 413);
    assert.equal(chatRequests, 0, "Stream controls must no longer poll chat");
    assert.deepEqual(errors, []);
    console.log("Owner/MFA gate, mobile/desktop layout, hover/focus help, preserved cameras/YouTube, no chat polling, guided Facebook readiness/publish/end/manual flow and hold cancellation: passed");
  } finally { await browser.close(); await prisma.$disconnect(); }
}
main().catch(e => { console.error(e); process.exitCode = 1; });
