import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {chromium,request} from 'playwright';
import {PrismaClient} from '@prisma/client';
import {createOwnerSession,requireIsolatedServer} from '../helpers/owner-session.mjs';
const base='http://localhost:3029';requireIsolatedServer(base);
const p=new PrismaClient();let owner,browser;
const profile='https://www.whatnot.com/user/treasure_hauls';
const shortCode='hauls-impact-'+createHash('sha256').update(profile).digest('hex').slice(0,24);
const tracking='https://whatnot.pxf.io/c/7857130/1943216/23513?test=isolated';
const userAgent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';
const api=await request.newContext({baseURL:base,timeout:120000,userAgent});
try{
 await p.affiliateLink.upsert({where:{shortCode},create:{network:'impact-whatnot',shortCode,productUrl:profile,affiliateUrl:tracking},update:{affiliateUrl:tracking,isActive:true}});
 assert.equal((await api.get('/api/live/impact')).status(),401);
 assert.equal((await api.post('/api/live/impact')).status(),401);
 const go=async(headers={})=>(await api.get('/go/show?show=missing',{maxRedirects:0,headers})).headers().location;
 assert.equal(await go(),profile);
 assert.equal(await go({referer:'https://facebook.com/example'}),profile);
 assert.equal(await go({referer:base+'/live?utm_source=facebook'}),tracking);
 assert.equal(await go({referer:base+'/live', 'user-agent':'facebookexternalhit/1.1'}),profile);
 assert.equal((await api.get('/go/whatnot',{maxRedirects:0,headers:{referer:base+'/live'}})).headers().location,'https://www.whatnot.com/invite/treasure_hauls');
 await p.affiliateLink.update({where:{shortCode},data:{isActive:false}});
 assert.equal(await go({referer:base+'/live'}),profile);
 browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:390,height:844},userAgent});let tagLoads=0;
 await context.route('https://utt.impactcdn.com/**',async route=>{tagLoads++;await route.fulfill({contentType:'application/javascript',body:'window.__impactTagLoaded=true;'});});
 const page=await context.newPage();page.setDefaultTimeout(120000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/live',{waitUntil:'networkidle'});
 assert.equal(tagLoads,0);await page.getByText('Affiliate disclosure:',{exact:false}).first().waitFor();
 await page.getByRole('button',{name:'Allow affiliate measurement'}).click();await page.waitForFunction(()=>window.__impactTagLoaded===true);assert.equal(tagLoads,1);
 await page.getByRole('link',{name:'Privacy details'}).click();await page.waitForURL('**/privacy#treasure-hauls');assert.equal(await page.evaluate(()=>window.__impactTagLoaded),undefined);
 await page.goto(base+'/live',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__impactTagLoaded===true);assert.equal(tagLoads,2);
 await page.getByRole('button',{name:'Turn off affiliate measurement'}).click();await page.waitForLoadState('networkidle');await page.getByRole('button',{name:'Allow affiliate measurement'}).waitFor();assert.equal(tagLoads,2);assert.equal(await page.evaluate(()=>window.__impactTagLoaded),undefined);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'/tmp/hauls-impact-mobile.png',fullPage:true});
 owner=await createOwnerSession(p,base);
 const admin=await request.newContext({baseURL:base,timeout:120000,extraHTTPHeaders:{Cookie:owner.cookie,Origin:base}});
 assert.equal((await admin.get('/api/live/impact')).status(),200);
 assert.equal((await admin.post('/api/live/impact',{headers:{Origin:'https://evil.invalid'}})).status(),403);
 await context.addCookies(owner.cookie.split('; ').map(pair=>{const i=pair.indexOf('=');return{name:pair.slice(0,i),value:pair.slice(i+1),url:base};}));
 await page.goto(base+'/stream/growth',{waitUntil:'networkidle'});await page.getByRole('heading',{name:'Whatnot affiliate · Impact'}).waitFor();assert.equal(tagLoads,2);
 const report=await admin.get('/api/live/report');assert.match(await report.text(),/Approved commission is not cash received/);
 assert.deepEqual(errors,[]);
 await admin.dispose();console.log('PASS: affiliate/fallback/bot/source redirects; invite isolation; disclosure; consent/revoke/private navigation; owner auth/CSRF; affiliate report');
}finally{await browser?.close();await owner?.cleanup();await p.affiliateLink.deleteMany({where:{shortCode}});await api.dispose();await p.$disconnect();}
