import test, { after } from "node:test";
import assert from "node:assert/strict";
import { parseWhatnotSchedule, WHATNOT_SELLER_ID } from "../../lib/live/schedule-core";
import { canPromote, centralInstant } from "../../lib/live/campaign";
import { reconcileWhatnotSchedule } from "../../lib/live/schedule-sync";
import { prisma } from "../../lib/prisma";
if (!process.env.DATABASE_URL?.includes("127.0.0.1:55449/tolley_live_growth_test")) throw new Error("Isolated test database required");
const uuid = "ee8864b7-82e7-43c6-967b-4f1bd9cfc28f";
const stamp = Date.now() + 2 * 86400000;
const item = { id: uuid, title: "The Random Finds!", startTime: stamp, userId: WHATNOT_SELLER_ID, status: "CREATED", isHiddenBySeller: false, minEligibleLoyaltyTier: null };
const payload = (nodes: unknown[] = [item], hasNextPage = false) => ({ data: { upcomingLives: { edges: nodes.map(node => ({ node })), pageInfo: { hasNextPage } } } });
test("observed seller schedule requires complete data and excludes restricted shows", () => {
  const shows = parseWhatnotSchedule(payload(), WHATNOT_SELLER_ID);
  assert.equal(shows[0].startsAt.getTime(), stamp);
  assert.equal(shows[0].whatnotUrl, `https://www.whatnot.com/live/${uuid}`);
  assert.throws(() => parseWhatnotSchedule(payload(), "another-seller"));
  assert.throws(() => parseWhatnotSchedule(payload([{ ...item, userId: "another-seller" }]), WHATNOT_SELLER_ID));
  assert.throws(() => parseWhatnotSchedule(payload([item], true), WHATNOT_SELLER_ID));
  assert.throws(() => parseWhatnotSchedule({ ...payload(), errors: [{ message: "partial" }] }, WHATNOT_SELLER_ID));
  assert.throws(() => parseWhatnotSchedule(payload([item, item]), WHATNOT_SELLER_ID));
  assert.throws(() => parseWhatnotSchedule({}, WHATNOT_SELLER_ID));
  assert.equal(parseWhatnotSchedule(payload([{ ...item, isHiddenBySeller: true }]), WHATNOT_SELLER_ID).length, 0);
  assert.equal(parseWhatnotSchedule(payload([{ ...item, minEligibleLoyaltyTier: 1 }]), WHATNOT_SELLER_ID).length, 0);
  assert.equal(parseWhatnotSchedule(payload([{ ...item, startTime: 1000 }]), WHATNOT_SELLER_ID).length, 0);
  assert.equal(centralInstant("2026-09-28", "20:31").getTime(), 1790645460000, "observed Whatnot timestamp is Monday 8:31 PM Central");
});
test("schedule replay, revisions, removals, owner holds and promotion freshness", async () => {
  await prisma.liveCampaignPost.deleteMany(); await prisma.liveShow.deleteMany();
  await prisma.liveSettings.upsert({ where: { id: "treasure-hauls" }, create: {}, update: {} });
  await prisma.liveSettings.update({ where: { id: "treasure-hauls" }, data: { campaignPaused: false, bindings: { facebook: { accountId: "test-haul", label: "Test" } } } });
  let shows = parseWhatnotSchedule(payload(), WHATNOT_SELLER_ID);
  assert.equal((await reconcileWhatnotSchedule(shows)).imported, 1);
  assert.equal((await reconcileWhatnotSchedule(shows)).imported, 0);
  assert.equal(await prisma.liveCampaignPost.count(), 4);
  const preview = await prisma.liveCampaignPost.findFirstOrThrow({ where: { kind: "preview" } });
  assert.equal(preview.status, "queued");
  const poll = await prisma.liveCampaignPost.findFirstOrThrow({ where: { kind: "poll" } });
  await prisma.liveCampaignPost.update({ where: { id: poll.id }, data: { status: "held" } });
  shows = parseWhatnotSchedule(payload([{ ...item, title: "Rescheduled finds", startTime: stamp + 86400000 }]), WHATNOT_SELLER_ID);
  assert.equal((await reconcileWhatnotSchedule(shows)).changed, 1);
  const revised = await prisma.liveCampaignPost.findUniqueOrThrow({ where: { id: preview.id } });
  assert.equal(+revised.dueAt, stamp + 86400000 - 121 * 60000);
  assert.match(revised.caption, /Rescheduled finds/);
  assert.equal((await prisma.liveCampaignPost.findUniqueOrThrow({ where: { id: poll.id } })).status, "held");
  const show = await prisma.liveShow.findUniqueOrThrow({ where: { id: shows[0].id } });
  assert.equal(canPromote(show), true);
  assert.equal(canPromote({ ...show, confirmedUntil: new Date(Date.now() - 1) }), false);
  assert.equal(canPromote({ ...show, id: "manual-show", confirmedUntil: null }), true);
  await assert.rejects(reconcileWhatnotSchedule([], new Date(Date.now() - 3600000)));
  assert.equal((await reconcileWhatnotSchedule([])).removed, 1);
  assert.equal((await prisma.liveShow.findUniqueOrThrow({ where: { id: show.id } })).status, "source_missing");
  assert.equal((await prisma.liveCampaignPost.findUniqueOrThrow({ where: { id: preview.id } })).status, "canceled");
  await reconcileWhatnotSchedule(shows);
  assert.equal((await prisma.liveCampaignPost.findUniqueOrThrow({ where: { id: preview.id } })).status, "queued");
  await prisma.liveCampaignPost.update({ where: { id: preview.id }, data: { status: "posting" } });
  await reconcileWhatnotSchedule(parseWhatnotSchedule(payload(), WHATNOT_SELLER_ID));
  assert.equal((await prisma.liveCampaignPost.findUniqueOrThrow({ where: { id: preview.id } })).status, "uncertain");
  await prisma.liveShow.update({ where: { id: show.id }, data: { status: "canceled" } });
  await reconcileWhatnotSchedule(shows);
  assert.equal((await prisma.liveShow.findUniqueOrThrow({ where: { id: show.id } })).status, "canceled");
  await prisma.liveCampaignPost.deleteMany(); await prisma.liveShow.deleteMany();
});
after(() => prisma.$disconnect());
