"use client";
import { useState } from "react";
import { formatShowTime, REFERRAL_URL, SHOW_TAGLINE } from "@/lib/live/campaign";
import { parseSalesCsv, saleAmount } from "@/lib/live/sales-import";
type Save = (body: unknown) => Promise<boolean>;
type Campaign = { id: string; accountId: string; kind: string; platform: string; caption: string; status: string; dueAt: string; expiresAt: string; manual: boolean; mediaUrl: string | null; error: string | null; url: string | null };
type Deal = { id: string; item: string; priceCents: number; soldAt: string; verified: boolean };
type Account = { platform: string; platformAccountId: string | null; platformUsername: string | null };
export type CampaignData = { campaigns: Campaign[]; deals: Deal[]; accounts: Account[]; heartbeat: { createdAt: string } | null };
export function CampaignPanel({ data, paused, busy, save }: { data: CampaignData; paused: boolean; busy: boolean; save: Save }) {
  return <section className="growth-box"><h2>The 8:31 campaign</h2><p><a href="/treasure-hauls/launch-kit.md" download>Download launch copy</a> · <a href="/treasure-hauls/30-day-calendar.csv" download>Download 30-day calendar</a></p><p>Morning highlight · 2 PM poll · 6:30 PM preview · 8:15 PM countdown · confirmed-live Story. Times are Central. Feed posts share a two-per-day limit with the clip publisher.</p><p>Campaign publishing: <b>{paused ? "paused" : "enabled"}</b>. Worker: {data.heartbeat ? new Date(data.heartbeat.createdAt).toLocaleString() : "not checked yet"}.</p><button className="growth-btn" disabled={busy} onClick={() => void save({ action: "campaign_pause", paused: !paused })}>{paused ? "Enable campaign queue" : "Pause campaign queue"}</button>
    <details><summary>Connect a dedicated haul account</summary><p>Keep other businesses for weekly crossover posts. This checks the selected account with the platform before saving its binding.</p><form className="growth-form" onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); const [platform, accountId] = String(f.get("account")).split("|"); await save({ action: "bind", platform, accountId, confirmHaulAccount: f.get("confirm") === "on" }); }}><label>Connected account<select name="account" required><option value="">Choose account</option>{data.accounts.map(a => <option key={`${a.platform}:${a.platformAccountId}`} value={`${a.platform.startsWith("facebook_page:") ? "facebook" : a.platform}|${a.platformAccountId}`}>{a.platformUsername || a.platformAccountId} ({a.platform})</option>)}</select></label><label><span><input type="checkbox" required name="confirm" style={{ width: "auto" }}/> This is a dedicated Treasure Hauls account.</span></label><button disabled={busy}>Verify and bind account</button></form><a href="/social">Manage social connections ↗</a></details>
    <details><summary>Brand copy, weekly crossover and referral invitation</summary><p><b>Bio:</b> Treasure Hauls • {SHOW_TAGLINE} Most evenings at 8:31 PM Central. Next-business-day shipping. Free KC-area pickup by arrangement. Confirmed dates: tolley.io/live</p><p><b>Pinned introduction:</b> Your evenings just found a new hangout. We’re Jared and Ruthann, and this is Treasure Hauls: real finds, unexpected deals, and a table full of surprises. Most evenings at 8:31 Central. Check our next confirmed show at tolley.io/live and bookmark it on Whatnot.</p><p><b>Weekly crossover:</b> A little of what we’ve been building after hours: Treasure Hauls! Come hang with us on Whatnot, usually at 8:31 Central. See this week’s confirmed dates and highlights: https://www.tolley.io/live?utm_source=weekly_crossover</p><p><b>Manual referral invitation:</b> New to Whatnot? Come hang with Treasure Hauls. Join through our invite: {REFERRAL_URL}. We may earn referral credit; eligibility and current offers are shown by Whatnot.</p><p>Referral invitations are shared manually. Automated posts use show links. Native Story polls and stickers are prepared here and posted in the platform app.</p><a href="/live/poster?format=story" target="_blank" rel="noreferrer">Download evergreen Story artwork ↗</a> · <a href="/live/poster" target="_blank" rel="noreferrer">Feed artwork ↗</a> · <a href="/live/poster?format=cover" target="_blank" rel="noreferrer">Facebook cover ↗</a></details>
    <details className="growth-box"><summary>Add a fact, verified recap, or weekly crossover</summary><form className="growth-form" onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); await save({ action: "campaign_custom", kind: f.get("kind"), platform: f.get("platform"), accountId: f.get("accountId"), caption: f.get("caption"), sourceUrl: f.get("sourceUrl"), dealId: f.get("dealId"), date: f.get("date"), time: f.get("time") }); }}><label>Post type<select name="kind"><option value="fact">Product fact (manual)</option><option value="recap">Verified deal recap</option><option value="crossover">Weekly crossover (automatic on verified accounts)</option></select></label><label>Platform<select name="platform"><option value="facebook">Facebook</option><option value="instagram">Instagram</option></select></label><label>Crossover account (only for crossover)<select name="accountId"><option value="">Choose account</option>{data.accounts.map(a => <option key={a.platformAccountId} value={a.platformAccountId || ""}>{a.platformUsername || a.platformAccountId}</option>)}</select></label><label>Caption (recaps use the verified sale automatically)<textarea name="caption" required minLength={10} maxLength={1700} defaultValue="Come for the show. Stay for the steals. Next confirmed dates: https://www.tolley.io/live"/></label><label>Primary source URL (required for facts)<input type="url" name="sourceUrl"/></label><label>Verified deal (required for recaps)<select name="dealId"><option value="">Choose sale</option>{data.deals.filter(d => d.verified).map(d => <option key={d.id} value={d.id}>{d.item} — ${(d.priceCents / 100).toFixed(2)}</option>)}</select></label><label>Posting date (Central)<input type="date" name="date" required/></label><label>Posting time (Central)<input type="time" name="time" defaultValue="10:00" required/></label><button disabled={busy}>Prepare draft</button></form></details>
    <h3>Post queue</h3>{!data.campaigns.length && <p>Confirm a show below, then choose “Prepare campaign.”</p>}{data.campaigns.map(post => <CampaignEditor key={`${post.id}-${post.status}-${post.caption}`} post={post} accountLabel={data.accounts.find(a => a.platformAccountId === post.accountId)?.platformUsername || post.accountId} busy={busy} save={save}/>)}
    <h3>Verified past deals</h3>{data.deals.map(d => <p key={d.id}>{d.item} · ${(d.priceCents / 100).toFixed(2)} · {d.verified ? "public" : "hidden"} {d.verified && <button disabled={busy} onClick={() => void save({ action: "deal_hide", id: d.id })}>Hide</button>}<br/><small>Recap: {d.item} sold for ${(d.priceCents / 100).toFixed(2)} on {formatShowTime(new Date(d.soldAt))}. Past sale; shipping/tax extra. Every show brings different finds.</small></p>)}
  </section>;
}
function CampaignEditor({ post, accountLabel, busy, save }: { post: Campaign; accountLabel: string; busy: boolean; save: Save }) {
  const [caption, setCaption] = useState(post.caption); const [url, setUrl] = useState(""); const [copied, setCopied] = useState(false);
  const editable = ["draft", "queued", "held", "manual"].includes(post.status);
  return <details className="growth-box"><summary>{accountLabel} · {post.platform} · {post.kind} · {formatShowTime(new Date(post.dueAt))} · {post.status}</summary><div className="growth-form"><label>Caption<textarea rows={5} maxLength={2200} value={caption} onChange={e => setCaption(e.target.value)} readOnly={!editable}/></label><div className="growth-actions"><button type="button" onClick={() => void navigator.clipboard.writeText(caption).then(() => setCopied(true)).catch(() => setCopied(false))}>{copied ? "Copied" : "Copy caption"}</button>{editable && <><button disabled={busy} onClick={() => void save({ action: "campaign_edit", id: post.id, caption })}>Save draft</button>{!post.manual && <button disabled={busy} onClick={() => void save({ action: "campaign_queue", id: post.id, caption })}>Queue this post</button>}<button disabled={busy} onClick={() => void save({ action: "campaign_hold", id: post.id })}>Hold</button></>}</div>{post.mediaUrl && <a href={post.mediaUrl} target="_blank" rel="noreferrer">Open artwork ↗</a>}{post.error && <p role="status">{post.error}</p>}{post.url && <a href={post.url} target="_blank" rel="noreferrer">View published post ↗</a>}{["manual", "uncertain"].includes(post.status) && <><label>Published post link<input value={url} onChange={e => setUrl(e.target.value)} type="url" placeholder="Paste after verifying it on the platform"/></label><button disabled={busy || !url} onClick={() => void save({ action: "campaign_posted", id: post.id, url })}>Record verified publication</button></>}<small>Expires {formatShowTime(new Date(post.expiresAt))}. Live announcements require verified Whatnot live status.</small></div></details>;
}
export function ResultsImport({ showId, busy, save }: { showId: string; busy: boolean; save: Save }) {
  const [csv, setCsv] = useState<ReturnType<typeof parseSalesCsv> | null>(null); const [file, setFile] = useState(""); const [error, setError] = useState("");
  return <details className="growth-box"><summary>Import actual sale prices and audience results</summary><p>Select a Whatnot CSV export, map its item and per-item sold-price columns, and confirm the completed sale date. Buyer information stays in your browser. Import only completed, non-refunded sales.</p><form className="growth-form" onSubmit={async e => { e.preventDefault(); setError(""); try { if (!csv) return; const f = new FormData(e.currentTarget); const itemCol = Number(f.get("item")), priceCol = Number(f.get("price")); if (itemCol === priceCol) throw new Error("Choose different item and price columns"); const soldAt = new Date(String(f.get("soldAt"))).toISOString(); const deals = csv.rows.map((row, index) => ({ showId, item: row[itemCol]?.trim(), price: saleAmount(row[priceCol] || ""), soldAt, evidence: `${file} row ${index + 2}`, verified: true })); if (await save({ action: "deals_import", deals })) setCsv(null); } catch (e) { setError(e instanceof Error ? e.message : "Invalid export"); } }}><label>Sales export (up to 100 rows)<input type="file" accept=".csv,text/csv" onChange={async e => { setError(""); try { const f = e.target.files?.[0]; if (!f) return; if (f.size > 1000000) throw new Error("Use a CSV under 1 MB"); const parsed = parseSalesCsv(await f.text()); if (parsed.rows.length > 100) throw new Error("Import up to 100 completed sales at a time"); setCsv(parsed); setFile(f.name); } catch (err) { setCsv(null); setError(err instanceof Error ? err.message : "Invalid CSV"); } }}/></label>{csv && <><p>{csv.rows.length} rows loaded. Confirm the correct columns before publishing prices.</p><label>Item title column<select name="item">{csv.headers.map((h, i) => <option key={i} value={i}>{h}</option>)}</select></label><label>Per-item sold price column<select name="price">{csv.headers.map((h, i) => <option key={i} value={i}>{h}</option>)}</select></label><label>Sale date/time (device timezone)<input name="soldAt" type="datetime-local" required/></label><label><span><input type="checkbox" required style={{ width: "auto" }}/> I verified these are actual completed USD sale prices, excluding shipping and tax.</span></label><button disabled={busy}>Import verified deal cards</button></>}{error && <p role="alert">{error}</p>}</form>
    <form className="growth-form" onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); await save({ action: "metrics", id: showId, metrics: { viewers: f.get("viewers") === "" ? null : Number(f.get("viewers")), bookmarks: f.get("bookmarks") === "" ? null : Number(f.get("bookmarks")), source: f.get("source"), measuredAt: new Date().toISOString() } }); }}><label>Whatnot reported viewers<input type="number" min="0" step="1" name="viewers"/></label><label>Whatnot reported bookmarks<input type="number" min="0" step="1" name="bookmarks"/></label><label>Source / metric definition<input name="source" required minLength={3} placeholder="Seller Hub show analytics; total viewers"/></label><button disabled={busy}>Save audience results</button></form>
  </details>;
}
