"use client";
import { useEffect, useState } from "react";
type Summary = { configured: boolean; checkedAt: string | null; snapshot: { contractStatus: string; since: string; until: string; actions: number; groups: { state: string; currency: string; actions: number; commission: number }[] } | null };
export default function ImpactPanel() {
  const [data,setData]=useState<Summary|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  async function load(sync=false) { setBusy(true);setError("");try { const r=await fetch("/api/live/impact",{method:sync?"POST":"GET",cache:"no-store"});if(!r.ok)throw new Error(sync?"Impact sync failed. Previous figures remain available.":"Impact report could not be loaded.");setData(await r.json()); }catch(e){setError((e as Error).message);}finally{setBusy(false);} }
  useEffect(()=>{void load();},[]);
  return <section className="growth-box"><h2>Whatnot affiliate · Impact</h2><p>{data?.configured?"Connected · daily reporting sync":"Connection not yet verified"}. Buyer referral credit and show sales are reported separately.</p>{data?.snapshot && <><p>Contract: {data.snapshot.contractStatus} · {data.snapshot.actions} attributed actions in the 30-day window ending {new Date(data.snapshot.until).toLocaleString()}.</p>{data.snapshot.groups.map(g=><p key={`${g.state}-${g.currency}`}>{g.state}: {g.actions} actions · {g.commission.toFixed(2)} {g.currency} commission</p>)}<p>Last successful sync: {data.checkedAt?new Date(data.checkedAt).toLocaleString():"Unknown"}. Approved commissions are not cash received; pending amounts can change. Cash paid is not imported.</p></>}<p>Invite links are excluded from affiliate payouts. Paid ads must follow the Whatnot contract: no trademark bidding, Whatnot-name ad copy, or direct affiliate destinations. No ad purchase is automated.</p><button className="growth-btn" disabled={busy || !data?.configured} onClick={()=>void load(true)}>{busy?"Checking Impact…":"Sync Impact and prepare show links"}</button> · <a href="https://app.impact.com/">Open Impact ↗</a>{error&&<p role="alert">{error}</p>}</section>;
}
