"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { contribution, ledgerSchema } from "@/lib/live/core";
import { CampaignPanel, ResultsImport, type CampaignData } from "./campaign-ui";
import { CAMPAIGN_BUDGET } from "@/lib/live/campaign";
import type { Ledger } from "@/lib/live/core";
import ImpactPanel from "./impact-panel";
type Show = { id: string; title: string; startsAt: string; category: string; durationMin: number; whatnotUrl: string; status: string; ledger: unknown; metrics: { viewers?: number; bookmarks?: number; source?: string } };
type Clip = { id: string; title: string; status: string; review: { reason?: string }; publications: { platform: string; status: string; url?: string; error?: string }[] };
type Data = CampaignData & { scheduleSync?: { createdAt: string; meta: { status: string; count?: number; message?: string } } | null; settings: { campaignPaused: boolean; publishingPaused: boolean; bindings: Record<string,{ accountId: string; label: string }> } | null; shows: Show[]; clips: Clip[]; clicks: { event: string; label: string; _count: number }[] };
const money = (n: number) => n.toLocaleString("en-US", { style: "currency", currency: "USD" });
export default function Growth() {
  const [data,setData] = useState<Data|null>(null); const [error,setError] = useState(""); const [busy,setBusy] = useState(false);
  async function load() { const r = await fetch("/api/live/manage", { cache: "no-store" }); if (!r.ok) throw new Error("Sign in with your owner account to load show management."); setData(await r.json()); }
  useEffect(() => { void load().catch(e => setError(e.message)); }, []);
  async function save(body: unknown) { setBusy(true); setError(""); try { const r = await fetch("/api/live/manage", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!r.ok) throw new Error((await r.json()).error); await load(); return true; } catch(e) { setError(e instanceof Error ? e.message : "Save failed"); return false; } finally { setBusy(false); } }
  const spent = (data?.shows || []).reduce((sum,s) => { const l=ledgerSchema.safeParse(s.ledger);return sum+(l.success?l.data.ads:0); },0);
  return <main style={{ maxWidth: 950, margin: "auto", padding: 24, background: "#0b1220", color: "#eef", minHeight: "100vh" }}><style>{`.growth-form{display:grid;gap:12px;margin:20px 0}.growth-actions{display:flex;gap:10px;flex-wrap:wrap}.growth-form textarea,.growth-form input,.growth-form select{background:#17243a;color:#fff;border:1px solid #65758b;border-radius:6px;padding:10px;width:100%}.growth-form label{font-size:13px;display:grid;gap:6px}.growth-form button,.growth-btn{background:#cee976;color:#182118;border:0;border-radius:6px;padding:10px 14px;cursor:pointer}.growth-box{border:1px solid #384353;border-radius:8px;padding:18px;margin:16px 0}.growth-costs{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:12px}button:disabled{opacity:.5}`}</style>
    <Link href="/stream">← Control room</Link> · <Link href="/live">Public live page ↗</Link><h1 style={{fontSize:30,marginTop:24}}>Treasure Hauls · growth</h1><p>Most evenings at 8:31 PM Central. The schedule sync checks Whatnot daily and before reminders.</p>{error && <p role="alert" style={{color:"#ffb4a5"}}>{error}</p>}
    <section className="growth-box"><h2>Whatnot schedule sync</h2><p>Create or change your shows in Whatnot. The saved Seller Hub session checks every four hours at :15, plus 6:15 PM and 8:05 PM Central. Public shows appear here automatically and their feed previews enter the campaign queue. Story stickers remain manual.</p><p>{data?.scheduleSync ? `Last check: ${new Date(data.scheduleSync.createdAt).toLocaleString("en-US", {timeZone:"America/Chicago"})} Central · ${Date.now()-Date.parse(data.scheduleSync.createdAt)>6*3600000 ? "overdue" : data.scheduleSync.meta.status} · ${data.scheduleSync.meta.count ?? "unknown"} upcoming shows` : "Waiting for the first schedule check."}</p>{data?.scheduleSync?.meta.message && <p role="status">{data.scheduleSync.meta.message}</p>}<p>A failed check preserves saved shows. Automatically imported schedules stop being promoted after six hours without verification. A scheduled show does not mark you live.</p><details><summary>Add a show manually</summary><p>Optional fallback: save a draft, then confirm its date.</p><form className="growth-form" onSubmit={async e => {e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(await save({action:"show",show:{title:f.get("title"),category:f.get("category"),centralDate:f.get("centralDate"),centralTime:f.get("centralTime"),durationMin:Number(f.get("durationMin")),whatnotUrl:f.get("whatnotUrl")}})) form.reset();}}><label>Show title<input name="title" required minLength={3} maxLength={120} placeholder="Tested gadgets & garage finds"/></label><label>Theme<select name="category"><option>Electronics</option><option>Home &amp; Garden</option><option>Estate / mixed finds</option></select></label><label>Show date (Central)<input type="date" name="centralDate" required/></label><label>Start time (Central)<input type="time" name="centralTime" defaultValue="20:31" required/></label><label>Length<select name="durationMin"><option value="60">1 hour</option><option value="120">2 hours</option><option value="180">3 hours</option></select></label><label>Whatnot show URL<input name="whatnotUrl" type="url" required placeholder="https://www.whatnot.com/live/…"/></label><button disabled={busy}>Save show draft</button></form></details></section>
    {data && <CampaignPanel data={data} paused={data.settings?.campaignPaused !== false} busy={busy} save={save}/>}
    <ImpactPanel/>
    <section className="growth-box"><h2>Automatic clips</h2><p>{data?.settings?.publishingPaused === false ? "Publishing enabled · when the campaign is enabled, one morning highlight shares the feed limit with the evening preview." : "Publishing paused."} Only clips inside a confirmed public show window and passing the content checks are eligible. Confirm the show live here when you start; rehearsal footage stays local. Unknown publish results are held for reconciliation, never blindly retried.</p><p>Accounts: {Object.entries(data?.settings?.bindings || {}).map(([p,b]) => `${p}: ${b.label}`).join(" · ") || "No verified accounts bound"}</p><button className="growth-btn" disabled={busy || !data} onClick={()=>void save({action:"pause",paused:data?.settings?.publishingPaused === false})}>{data?.settings?.publishingPaused === false ? "Pause publishing" : "Enable publishing"}</button>{data?.clips.map(c=><div className="growth-box" key={c.id}><b>{c.title}</b> · {c.status}<p>{c.review.reason}</p>{c.publications.map(p=><p key={p.platform}>{p.platform}: {p.status} {p.url && <a href={p.url}>View ↗</a>} {p.error}</p>)}<button className="growth-btn" disabled={busy} onClick={()=>void save({action:"hold",id:c.id})}>Hold clip</button></div>)}</section>
    <section className="growth-box"><h2>First 30 days · $300 ceiling</h2><p>Recorded ad spend: {money(spent)} · Ad allowance remaining: {money(Math.max(0,CAMPAIGN_BUDGET.ads-spent))}{spent>CAMPAIGN_BUDGET.ads?" · Ad allowance exceeded":""}</p><p>$200 ads · $50 production · $50 reserve. Begin with organic results. Paid tests: $10/day, $50 per test; stop after $50 if no measured show clicks. Advertising purchases remain manual. No spend is initiated by this dashboard.</p><p>Compare contribution per live hour with similar unpaid shows. Show-link clicks are not purchases or incremental profit.</p><a href="/api/live/report">Download weekly report (CSV) ↗</a></section>
    {data?.shows.map(s=><section className="growth-box" key={s.id}><h2>{s.title}</h2><p><b>{s.status}</b> · {new Date(s.startsAt).toLocaleString("en-US",{timeZone:"America/Chicago"})} Central</p><div style={{display:"flex",gap:12,flexWrap:"wrap"}}>{!["live","ended"].includes(s.status) && <><button className="growth-btn" disabled={busy || s.status === "confirmed"} onClick={()=>void save({action:"schedule_confirm",id:s.id})}>Confirm show date</button><button className="growth-btn" disabled={busy || s.status !== "confirmed"} onClick={()=>void save({action:"pack",id:s.id})}>Prepare campaign</button><button className="growth-btn" disabled={busy} onClick={()=>void save({action:"cancel_show",id:s.id})}>Cancel show promotion</button></>}<button className="growth-btn" disabled={busy || !["confirmed","live"].includes(s.status)} onClick={()=>void save({action:"confirm",id:s.id})}>I verified this show is live on Whatnot</button><button className="growth-btn" disabled={busy} onClick={()=>void save({action:"end",id:s.id})}>Mark show ended on public page</button></div><p>These controls update the public listing only. They do not start or stop a stream.</p><ShowEdit show={s} busy={busy} save={save}/><ResultsImport showId={s.id} busy={busy} save={save}/>{s.metrics?.source && <p>Audience: {s.metrics.viewers ?? "unknown"} viewers · {s.metrics.bookmarks ?? "unknown"} bookmarks · {s.metrics.source}</p>}<LedgerForm show={s} busy={busy} save={save}/></section>)}
    <section className="growth-box"><h2>Whatnot outbound clicks · last 30 days</h2>{data?.clicks.map(c=><p key={`${c.event}-${c.label}`}>{c.event} / {c.label}: {c._count}</p>)}<p>Clicks are not verified signups or purchases.</p></section>
  </main>;
}
function LedgerForm({show,busy,save}:{show:Show;busy:boolean;save:(b:unknown)=>Promise<boolean>}) {
  const existing=ledgerSchema.safeParse(show.ledger);const summary=existing.success?contribution(existing.data):null;
  const fields: [keyof Omit<Ledger,"settled">,string][]=[["sales","Gross sales"],["fees","Actual platform fees"],["inventory","Inventory cost"],["fulfillment","Packing / seller shipping / transport"],["refunds","Refund costs"],["ads","Ad spend"],["labor","Labor cost"],["minutes","Live minutes"],["orders","Orders"]];
  return <details><summary style={{cursor:"pointer",marginTop:18}}>Show costs & results</summary>{summary&&<p>{existing.success&&existing.data.settled?"Settled":"Estimated"}: {money(summary.afterAds)} after ads, before labor · {money(summary.afterLabor)} after labor · {money(summary.perHour)}/hour. Break-even extra sales for this ad spend: {summary.breakEvenExtraSales===null?"No positive margin":money(summary.breakEvenExtraSales)}.</p>}<form className="growth-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await save({action:"ledger",id:show.id,ledger:{...Object.fromEntries(fields.map(([k])=>[k,Number(f.get(k))])),settled:f.get("settled")==="on"}});}}><div className="growth-costs">{fields.map(([k,label])=><label key={k}>{label}<input type="number" name={k} step={k==="orders"?"1":"0.01"} min={k==="minutes"?1:0} required defaultValue={existing.success?existing.data[k]:k==="inventory"?0:undefined}/></label>)}</div><label><span><input style={{width:"auto"}} type="checkbox" name="settled" defaultChecked={existing.success&&existing.data.settled}/> Reconciled against seller statement</span></label><button disabled={busy}>Save show results</button></form></details>;
}

function ShowEdit({show,busy,save}:{show:Show;busy:boolean;save:(b:unknown)=>Promise<boolean>}) {
 if (["live","ended"].includes(show.status)) return null;
 const parts = new Intl.DateTimeFormat("sv-SE",{timeZone:"America/Chicago",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(show.startsAt)).split(" ");
 return <details><summary>Edit / reschedule</summary><p>Rescheduling clears unsent reminders and returns the show to draft. Confirm the new date and prepare a fresh campaign.</p><form className="growth-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await save({action:"edit_show",id:show.id,show:{title:f.get("title"),category:show.category,durationMin:show.durationMin,whatnotUrl:f.get("whatnotUrl"),centralDate:f.get("date"),centralTime:f.get("time")}})}}><label>Title<input name="title" required defaultValue={show.title}/></label><label>Central date<input type="date" name="date" required defaultValue={parts[0]}/></label><label>Central time<input type="time" name="time" required defaultValue={parts[1]}/></label><label>Whatnot show URL<input type="url" name="whatnotUrl" required defaultValue={show.whatnotUrl}/></label><button disabled={busy}>Save revised show</button></form></details>;
}
