"use client";
import { useEffect, useState } from "react";
import type { growthReport } from "@/lib/growth/report";
type Data = JSONData<Awaited<ReturnType<typeof growthReport>>>;
type JSONData<T> = T extends Date ? string : T extends Array<infer U> ? JSONData<U>[] : T extends object ? { [K in keyof T]: JSONData<T[K]> } : T;
const stamp = (s: string) => new Date(s).toLocaleString("en-US", { timeZone: "America/Chicago" });
export default function GrowthReport() {
  const [period, setPeriod] = useState("today"), [data, setData] = useState<Data | null>(null), [error, setError] = useState("");
  async function refresh() { try { const r = await fetch(`/api/hq/growth?period=${period}`); if (!r.ok) throw Error(); setData(await r.json()); setError(""); } catch { setError("Report unavailable. Previous data may be stale; refresh to try again."); } }
  useEffect(() => { void refresh(); const t = setInterval(refresh, 60000); return () => clearInterval(t); }, [period]); // eslint-disable-line react-hooks/exhaustive-deps
  async function pause(control: string, paused: boolean) { const r = await fetch("/api/hq/growth", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ control, paused }) }); if (!r.ok) setError("Could not save the pause control."); else await refresh(); }
  const bindings = Object.entries((data?.settings?.bindings || {}) as Record<string,{accountId:string;label:string}>);
  const accountName = (id:string) => bindings.find(([,b])=>b.accountId===id)?.[1].label || id;
  const box = "rounded-xl border border-neutral-300 bg-white p-4 shadow-sm space-y-3";
  return <div className="space-y-6"><nav className="flex gap-4 flex-wrap">{[["today","Today"],["yesterday","Yesterday"],["7","7 days"],["30","30 days"]].map(([v,l]) => <button className="underline" aria-pressed={period === v} key={v} onClick={() => setPeriod(v)}>{l}</button>)}<a href="/stream/growth">Show controls</a><a href="/hq/discovery">Discovery & revenue</a><a href="/blog">Public blog</a></nav>{error && <p role="alert">{error}</p>}{!data ? <p>Loading evidence…</p> : <>
    <p>Report: {stamp(data.since)} – {stamp(data.until)}</p>
    <section className={box}><h2 className="text-xl">Automation</h2>{(["blogPaused", "announcementsPaused"] as const).map(key => { const paused = data.controls?.[key] ?? true; return <p key={key}>{key === "blogPaused" ? "Daily blog (9 AM Central)" : "Live announcements"}: {paused ? "paused" : "enabled"} <button className="underline" onClick={() => void pause(key, !paused)}>{paused ? "Enable" : "Pause"}</button></p>; })}<div>{bindings.map(([k,b])=><p key={k}>{b.label}: {k === "facebook" || k === "instagram" ? "start + 30-minute live reminders" : k.startsWith("crossover:facebook") || k.startsWith("crossover:instagram") ? "start announcement only" : "live announcement unsupported by this connector"}</p>)}</div><p>Clip publishing: {data.settings?.publishingPaused === false ? "enabled" : "paused"}. Campaign master: {data.settings?.campaignPaused === false ? "enabled" : "paused"}.</p>{data.health.length ? data.health.map(h => <p key={h.id}>{h.title}: {h.status} — {h.detail} · {stamp(h.updatedAt)}{h.kind === "utility" && <span className="block whitespace-pre-wrap break-words">{JSON.stringify(h.metadata)}</span>}</p>) : <p>No worker heartbeat has been received.</p>}</section>
    <section className={box}><h2 className="text-xl">Results</h2><p>Seller inquiries: {data.inquiries}. Published campaign posts: {data.campaigns.filter(c => c.status === "posted").length}. Published clips: {data.clips.filter(c => c.status === "posted").length}.</p>{data.clicks.map(c => <p key={`${c.event}:${c.label}`}>{c.event} · {c.label || "unattributed"}: {c._count}</p>)}{!data.clicks.length && <p>No recorded clicks in this period.</p>}<div>{data.visits.map(v=><p key={`${v.site}:${v.audience}`}>{v.site} page views ({v.audience}): {v._count}</p>)}</div><p>Social-platform views: unavailable. Buyer referral credits: unavailable. Seller referral bonuses: unavailable.</p>{data.impact ? <details><summary>Affiliate commission snapshot · {stamp(data.impact.createdAt)}</summary><pre className="whitespace-pre-wrap break-words">{JSON.stringify(data.impact.meta, null, 2)}</pre></details> : <p>Affiliate commissions: no collected snapshot.</p>}<p className="text-sm">{data.limitations}</p></section>
    <section className={box}><h2 className="text-xl">Activity and explanations</h2>{data.activity.map(a => <article key={a.id}><strong>{a.title}</strong> · {a.status} · {stamp(a.updatedAt)}<p>{a.detail} {a.url && <a className="underline" href={a.url}>View result</a>}</p></article>)}{!data.activity.length && <p>No worker activity recorded in this period.</p>}</section>
    <section className={box}><h2 className="text-xl">Where we posted</h2>{data.campaigns.map(p => <article key={p.id}><strong>{p.kind}</strong> · {p.platform} / {accountName(p.accountId)} · {p.status} · {stamp(p.dueAt)}<p>{p.error}</p>{p.url && <a className="underline" href={p.url}>View actual post</a>}<details><summary>Post and destination links</summary><p className="whitespace-pre-wrap break-words">{p.caption}</p></details></article>)}{data.clips.map(p => <p key={p.id}>{p.clip.title} · {p.platform} / {accountName(p.accountId)} · {p.status} {p.error} {p.url && <a className="underline" href={p.url}>View clip</a>}</p>)}{!data.clips.length && !data.campaigns.length && <p>No publishing records in this period.</p>}</section>
    <section className={box}><h2 className="text-xl">Build stories</h2>{data.stories.map(s => <p key={s.id}>{s.status === "published" ? <a className="underline" href={`/blog/${s.slug}`}>{s.title}</a> : s.title} · {s.status} · Text: {s.notificationStatus}{s.retrospective ? " · Retrospective" : ""}</p>)}{!data.stories.length && <p>No stories generated in this period.</p>}</section>
    <section className={box}><h2 className="text-xl">Show accounting</h2>{data.shows.map(s => <div key={s.id}><b>{s.title}</b> · {stamp(s.startsAt)}{s.result ? <p>{s.result.settled ? "Reconciled" : "Estimated"}: sales ${s.result.grossSales.toFixed(2)}, ads ${s.result.ads.toFixed(2)}, contribution after labor ${s.result.afterLabor.toFixed(2)}.</p> : <p>Costs and earnings not recorded.</p>}</div>)}</section>
  </>}</div>;
}
