"use client";
import { useEffect, useState } from "react";
import type { growthReport } from "@/lib/growth/report";
import { isHttpUrl } from "@/components/hq/types";
import styles from "./report.module.css";
type JSONData<T> = T extends Date ? string : T extends Array<infer U> ? JSONData<U>[] : T extends object ? { [K in keyof T]: JSONData<T[K]> } : T;
type Data = JSONData<Awaited<ReturnType<typeof growthReport>>>;
type Metric = "posts" | "clicks" | "views";
const ranges = [["7","7 days"],["today","Today"],["yesterday","Yesterday"],["30","30 days"]];
const number = (n:number) => n.toLocaleString("en-US");
const money = (n:number) => n.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
const dayKey = (s:string) => new Intl.DateTimeFormat("en-CA",{timeZone:"America/Chicago",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(s));
const stamp = (s:string) => new Date(s).toLocaleString("en-US",{timeZone:"America/Chicago",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});
const dayLabel = (s:string) => new Date(s+"T12:00:00Z").toLocaleDateString("en-US",{month:"short",day:"numeric",timeZone:"UTC"});
const platformName = (s:string) => ({facebook:"Facebook",instagram:"Instagram",youtube:"YouTube"}[s] || s);
const statusName = (s:string) => ({posted:"Posted",queued:"Waiting",posting:"Sending",draft:"Draft",manual:"Post manually",held:"Held",expired:"Skipped · expired",canceled:"Stopped",unsupported:"Not supported",uncertain:"Check result",published:"Published",no_speech:"No speech found",no_candidates:"No clips selected",checked:"Checked",scheduled:"Scheduled",verified:"Verified",collected:"Updated",retry:"Will retry",deferred:"Waiting",not_sent:"Not sent",accepted:"Text accepted",delivered:"Text delivered",pending:"Text pending",uncertain_send:"Check text"}[s] || s.replaceAll("_"," "));
const tone = (s:string) => ["posted","published","verified","delivered","checked","collected"].includes(s) ? styles.good : ["uncertain","held","no_speech","retry","failed","unavailable","undelivered"].includes(s) ? styles.warn : styles.neutral;
function Badge({status}:{status:string}) { return <span className={`${styles.badge} ${tone(status)}`}>{["posted","published","verified","delivered"].includes(status) ? "✓ " : ""}{statusName(status)}</span>; }
function LinkOut({url,children}:{url:string|null;children:React.ReactNode}) { return isHttpUrl(url) ? <a className={styles.link} href={url} target="_blank" rel="noreferrer">{children} ↗</a> : null; }
export default function GrowthReport() {
 const [period,setPeriod]=useState("7"),[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[reload,setReload]=useState(0),[busy,setBusy]=useState<string|null>(null);
 const [metric,setMetric]=useState<Metric>("posts"),[selected,setSelected]=useState<string|null>(null),[filter,setFilter]=useState("all");
 useEffect(()=>{
  const controller=new AbortController();let request=0;
  async function refresh(){const id=++request;try{const r=await fetch(`/api/hq/growth?period=${period}`,{signal:controller.signal});if(!r.ok)throw Error();const result=await r.json();if(!controller.signal.aborted && id===request){setData(result);setError("");setLoading(false);}}catch{if(!controller.signal.aborted && id===request){setError("Couldn’t load this report. Try refresh.");setLoading(false);}}}
  setLoading(true);setData(null);setSelected(null);void refresh();const timer=setInterval(refresh,60000);
  return()=>{controller.abort();clearInterval(timer);};
 },[period,reload]);
 async function pause(control:"blogPaused"|"announcementsPaused",paused:boolean){setBusy(control);try{const r=await fetch("/api/hq/growth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({control,paused})});if(!r.ok)throw Error();setReload(v=>v+1);}catch{setError("Couldn’t save that change. Try again.");}finally{setBusy(null);}}
 const rangeLabel=ranges.find(([key])=>key===period)?.[1] || "7 days";
 if(!data)return <section className={styles.dashboard}><header className={styles.header}><div><span className={styles.eyebrow}>TREASURE HAULS + YOUR BUILDS</span><h1>Growth at a glance</h1></div></header><div className={styles.loading} role="status">{loading ? "Loading your numbers…" : error}<button className={styles.button} onClick={()=>setReload(v=>v+1)}>Refresh</button></div></section>;
 const daily: Data["daily"]=[];const last=dayKey(new Date(new Date(data.until).getTime()-1).toISOString());
 for(let date=dayKey(data.since);date<=last;){daily.push(data.daily.find(d=>d.day===date) || {day:date,posts:0,clicks:0,views:0,inquiries:0,stories:0});const next=new Date(date+"T12:00:00Z");next.setUTCDate(next.getUTCDate()+1);date=next.toISOString().slice(0,10);}
 const total=(key:"posts"|"clicks"|"views"|"inquiries"|"stories")=>daily.reduce((sum,d)=>sum+d[key],0);
 const max=Math.max(1,...daily.map(d=>d[metric]));
 const allPosts=[...data.campaigns.map(p=>({...p,title:p.kind.startsWith("announce_") ? "Live announcement" : ({preview:"Show preview",crossover:"Business shout-out",recap:"Show recap",fact:"Resale tip",poll:"Show poll",countdown:"Show countdown",live:"Live show"}[p.kind] || "Show promotion")})),...data.clips.map(p=>({...p,title:p.clip.title,caption:"",dueAt:p.createdAt}))].sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt));
 const inRange=(date:string)=>date>=data.since && date<data.until;
 const posted=allPosts.filter(p=>p.status==="posted" && inRange(p.updatedAt));
 const counts=[allPosts.filter(p=>p.status==="posted").length,allPosts.filter(p=>["queued","posting","draft"].includes(p.status)).length,allPosts.filter(p=>p.status==="manual").length,allPosts.filter(p=>!["posted","queued","posting","draft","manual"].includes(p.status)).length];
 const sum=counts.reduce((a,b)=>a+b,0),a=sum?counts[0]/sum*100:0,b=sum?(counts[0]+counts[1])/sum*100:0,c=sum?(counts[0]+counts[1]+counts[2])/sum*100:0;
 const bindings=Object.entries((data.settings?.bindings||{}) as Record<string,{accountId:string;label:string}>);
 const accountName=(id:string)=>bindings.find(([,v])=>v.accountId===id)?.[1].label || "Connected account";
 const platforms=[...new Set([...bindings.map(([key])=>key.startsWith("crossover:")?key.split(":")[1]:key),...allPosts.map(p=>p.platform)])];
 const noSpeech=data.activity.filter(a=>a.status==="no_speech").length;
 const blogOn=data.controls?.blogPaused===false,announcementsOn=data.controls?.announcementsPaused===false && data.settings?.campaignPaused===false;
 const recordedShows=data.shows.filter(s=>s.result?.settled),revenue=recordedShows.reduce((v,s)=>v+(s.result?.grossSales||0),0);
 const utility=data.health.find(h=>h.id==="cordport-tool-health");const usage=utility?.metadata as {days?:{day:string;completed:number;cached:number}[]}|undefined;
 const checks=Array.isArray(usage?.days)?usage.days.filter(d=>d.day>=dayKey(data.since)&&d.day<=last).reduce((v,d)=>v+d.completed,0):null;
 const shown=(filter==="all"?posted:posted.filter(p=>p.platform===filter)).slice(0,6);
 return <section className={styles.dashboard} aria-label="Growth dashboard">
  <header className={styles.header}><div><span className={styles.eyebrow}>TREASURE HAULS + YOUR BUILDS</span><h1>Growth at a glance</h1><p>Your real results. One place. <a href="/hq/content-income">Content earnings & experiments →</a></p></div><div className={styles.headerRight}><div className={styles.ranges} aria-label="Report period">{ranges.map(([key,label])=><button key={key} aria-pressed={period===key} className={period===key?styles.chosen:""} onClick={()=>setPeriod(key)}>{label}</button>)}</div><span className={styles.small}>{dayLabel(dayKey(data.since))}{last!==dayKey(data.since)?` – ${dayLabel(last)}`:""} · Central time <button className={styles.refresh} onClick={()=>setReload(v=>v+1)} aria-label="Refresh growth report">↻</button></span></div></header>
  {error&&<div role="alert" className={styles.alert}>{error} Showing the last loaded numbers.</div>}
  <div className={styles.kpis}>
   {[{label:"Posts published",value:total("posts"),icon:"↗",color:styles.purple,note:"Across your accounts"},{label:"Show clicks",value:total("clicks"),icon:"↖",color:styles.blue,note:"Clicks to your Whatnot show"},{label:"Seller inquiries",value:total("inquiries"),icon:"＋",color:styles.green,note:"People asking you to sell"},{label:"Blog stories",value:total("stories"),icon:"✎",color:styles.orange,note:"Published on your blog"}].map(k=><article className={`${styles.kpi} ${k.color}`} key={k.label}><div><h2>{k.label}</h2><span aria-hidden="true" className={styles.kpiIcon}>{k.icon}</span></div><strong data-testid={`metric-${k.label}`}>{number(k.value)}</strong><p>{k.note}</p></article>)}
  </div>
  <div className={styles.statuses}>
   <a href="/stream/growth" className={`${styles.statusCard} ${noSpeech?styles.attention:styles.ready}`}><span className={styles.statusIcon} aria-hidden="true">{noSpeech?"!":"▶"}</span><div><b>{noSpeech?"Clips need attention":"Clip publishing"}</b><span>{noSpeech?`${noSpeech} recordings · no speech found`:data.settings?.publishingPaused===false?"Enabled · checked before posting":"Paused"}</span></div><span aria-hidden="true">→</span></a>
   <a href="#growth-controls" className={`${styles.statusCard} ${blogOn?styles.ready:styles.attention}`}><span className={styles.statusIcon} aria-hidden="true">✎</span><div><b>{blogOn?"Blog is on":"Blog is paused"}</b><span>Daily at 9 AM · text after publishing</span></div><span aria-hidden="true">↓</span></a>
   <a href="/stream/growth" className={`${styles.statusCard} ${announcementsOn?styles.ready:styles.attention}`}><span className={styles.statusIcon} aria-hidden="true">◉</span><div><b>{announcementsOn?"Live alerts are on":"Live alerts are paused"}</b><span>{announcementsOn?"Confirm live → start + 30-minute reminders":"Open show controls"}</span></div><span aria-hidden="true">→</span></a>
  </div>
  <div className={styles.chartGrid}>
   <section className={styles.panel} aria-label="Daily activity chart"><div className={styles.panelHeader}><div><h2>Activity by day</h2><p>{rangeLabel} · tap a bar</p></div><div className={styles.chartTabs}>{(["posts","clicks","views"] as Metric[]).map(m=><button key={m} aria-pressed={metric===m} className={metric===m?styles.chosen:""} onClick={()=>{setMetric(m);setSelected(null);}}>{m==="posts"?"Posts":m==="clicks"?"Show clicks":"Page views"}</button>)}</div></div>
    <div className={styles.chartSummary}><strong>{number(total(metric))}</strong><span>{metric==="posts"?"published":metric==="clicks"?"show clicks":"recorded page views"}</span></div>
    <div className={styles.chartScroll}><div className={styles.bars}>{daily.map(d=><button key={d.day} aria-label={`${dayLabel(d.day)}: ${d[metric]} ${metric}`} aria-pressed={selected===d.day} className={`${styles.barButton} ${selected===d.day?styles.selectedBar:""}`} onClick={()=>setSelected(d.day)}><span className={styles.barCount}>{number(d[metric])}</span><span className={styles.barTrack}><span className={`${styles.barFill} ${metric==="clicks"?styles.blueBar:metric==="views"?styles.greenBar:""}`} style={{height:d[metric]?`${Math.max(3,d[metric]/max*100)}%`:"0%"}} /></span><span className={styles.barDate}>{dayLabel(d.day)}</span></button>)}</div></div>
    <p className={styles.chartFoot} aria-live="polite">{selected?`${dayLabel(selected)}: ${number(daily.find(d=>d.day===selected)?.[metric]||0)} ${metric==="clicks"?"show clicks":metric==="views"?"page views":"posts"}`:total(metric)===0?"No recorded activity in this period.":"Each bar is a day. Numbers are recorded activity."}</p>
   </section>
   <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Post status</h2><p>{number(sum)} records in this period</p></div></div><div className={styles.donutWrap}><div className={styles.donut} role="img" aria-label={`Post status: ${counts[0]} posted, ${counts[1]} waiting, ${counts[2]} manual, ${counts[3]} skipped or held`} style={{background:sum?`conic-gradient(#6640c7 0% ${a}%,#2374d4 ${a}% ${b}%,#df9d20 ${b}% ${c}%,#c1c7d3 ${c}% 100%)`:"#e5e7ee"}}><div><strong>{counts[0]}</strong><span>posted</span></div></div><ul className={styles.legend}>{["Posted","Waiting","Post manually","Skipped / held"].map((label,i)=><li key={label}><i aria-hidden="true" style={{background:["#6640c7","#2374d4","#df9d20","#c1c7d3"][i]}}/><span>{label}</span><b>{counts[i]}</b></li>)}</ul></div></section>
  </div>
  <div className={styles.lowerGrid}>
   <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Where we posted</h2><p>Published posts · {rangeLabel.toLowerCase()}</p></div><span aria-hidden="true" className={styles.panelIcon}>↗</span></div><div className={styles.channels}>{platforms.map(platform=>{const count=posted.filter(p=>p.platform===platform).length;return <button className={styles.channel} key={platform} onClick={()=>{setFilter(platform);document.getElementById("growth-posts")?.scrollIntoView({block:"start"});}}><span className={`${styles.platform} ${styles[platform]||""}`} aria-hidden="true">{platform==="facebook"?"f":platform==="instagram"?"◎":"▶"}</span><div><b>{platformName(platform)}</b><div className={styles.channelTrack}><span style={{width:`${count/Math.max(1,posted.length)*100}%`,background:platform==="facebook"?"#2374d4":platform==="instagram"?"#a041ae":"#d34444"}}/></div></div><strong>{count}</strong><span aria-hidden="true">→</span></button>;})}</div><p className={styles.small}>YouTube text alerts are not supported.</p></section>
   <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Money & tools</h2><p>Recorded results only</p></div><span aria-hidden="true" className={styles.panelIcon}>$</span></div><div className={styles.miniStats}><div><span>Settled show sales</span><strong>{recordedShows.length?money(revenue):"Not recorded"}</strong><small>{recordedShows.length?`${recordedShows.length} settled shows · before costs`:"Add results in Show Controls"}</small></div><div><span>Cordport checks</span><strong>{checks===null?"Not connected":number(checks)}</strong><small>{utility?.status==="collected"?"Completed website checks":checks!==null?"Previous snapshot · needs refresh":"Waiting for a usage report"}</small></div></div><div className={styles.quickLinks}><a href="/stream/growth">Show controls →</a><a href="https://cordport.io/tools/website-check">Open checker ↗</a></div></section>
  </div>
  <section id="growth-posts" className={styles.panel}><div className={styles.panelHeader}><div><h2>See the actual posts</h2><p>Tap a post to open it</p></div><select aria-label="Filter published posts by platform" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All channels</option>{platforms.map(p=><option key={p} value={p}>{platformName(p)}</option>)}</select></div><div className={styles.postGrid}>{shown.map(p=><article className={styles.postCard} key={p.id}><div className={styles.postMeta}><span>{platformName(p.platform)}</span><Badge status={p.status}/></div><h3>{p.title}</h3><p>{accountName(p.accountId)}</p><time>{stamp(p.updatedAt)}</time><LinkOut url={p.url}>Open post</LinkOut></article>)}</div>{!shown.length&&<div className={styles.empty}>No published posts here yet.{period==="today"&&<button className={styles.button} onClick={()=>setPeriod("7")}>See the last 7 days</button>}</div>}</section>
  <details className={styles.details}><summary>More detail <span>All posts, activity & money</span></summary><div className={styles.detailBody}>
   <h2>All post records</h2><p className={styles.small}>Up to 500 records per source. Chart totals are not capped.</p>{allPosts.map(p=><div className={styles.detailRow} key={p.id}><div><b>{p.title}</b><p>{platformName(p.platform)} · {accountName(p.accountId)} · {stamp(p.dueAt)}</p></div><Badge status={p.status}/><LinkOut url={p.url}>Open</LinkOut>{(p.error||p.caption)&&<details><summary>Post details</summary><p>{p.error||p.caption}</p></details>}</div>)}
   <h2>Worker activity</h2>{data.activity.map(a=><div className={styles.detailRow} key={a.id}><div><b>{a.title}</b><p>{stamp(a.updatedAt)}</p></div><Badge status={a.status}/><details><summary>What happened?</summary><p>{a.detail}</p><LinkOut url={a.url}>View result</LinkOut></details></div>)}
   <h2>Blog stories</h2>{data.stories.length?data.stories.map(s=><div className={styles.detailRow} key={s.id}><b>{s.title}</b><Badge status={s.status}/><span>{statusName(s.notificationStatus)}</span>{s.status==="published"&&<a href={`/blog/${s.slug}`}>Read story →</a>}</div>):<p>No stories recorded in this period.</p>}
   <h2>Show accounting</h2>{data.shows.map(s=><div className={styles.detailRow} key={s.id}><b>{s.title}</b><span>{s.result?`${s.result.settled?"Settled":"Estimate"} · Sales ${money(s.result.grossSales)} · Ads ${money(s.result.ads)} · After labor ${money(s.result.afterLabor)}`:"Costs and earnings not recorded"}</span></div>)}
   <p>Affiliate reporting: {data.impact?`snapshot collected ${stamp(data.impact.createdAt)}`:"no snapshot collected"}. Approved commission is not a cash payout. <a href="/stream/growth">Open affiliate reporting →</a></p>
   <p className={styles.small}>Show clicks count show-link events once, without adding affiliate tracking events. Page views cover the show and blog; known operator/customer visits are excluded. Historical unknown audiences remain included. Posting dates use the publishing record’s last update. Platform views and referral credits are not connected.</p>
  </div></details>
  <section id="growth-controls" className={styles.panel}><div className={styles.panelHeader}><div><h2>Automation controls</h2><p>You’re in control</p></div></div><div className={styles.controlGrid}>{(["blogPaused","announcementsPaused"] as const).map(key=>{const paused=data.controls?.[key]!==false;return <div key={key} className={styles.control}><span aria-hidden="true" className={`${styles.controlDot} ${paused?styles.off:""}`}/><div><b>{key==="blogPaused"?"Daily blog":"Live announcements"}</b><p>{paused?"Paused":"Enabled"}</p></div><button disabled={busy===key} className={styles.button} onClick={()=>void pause(key,!paused)}>{busy===key?"Saving…":paused?"Enable":"Pause"}</button></div>;})}</div><details className={styles.accountDetails}><summary>Connected accounts & worker checks</summary>{bindings.map(([key,b])=><p key={key}><b>{b.label}</b> · {key==="facebook"||key==="instagram"?"Start + 30-minute reminders":key.startsWith("crossover:facebook")||key.startsWith("crossover:instagram")?"Start only":"Text alerts unsupported"}</p>)}{data.health.map(h=><p key={h.id}>{h.title} · {statusName(h.status)} · {stamp(h.updatedAt)}</p>)}<p>Campaign master: {data.settings?.campaignPaused===false?"Enabled":"Paused"}. <a href="/stream/growth">Open show controls →</a></p></details></section>
 </section>;
}
