"use client";

export default function DossierBrief({ summary }: { summary: string | null }) {
  if (!summary) return null;

  return (
    <div>
      <div className="prose prose-invert prose-sm max-w-none">
        <div className="whitespace-pre-wrap text-sm text-white/80 leading-relaxed">
          {summary}
        </div>
      </div>
      <p className="mt-3 text-[0.6rem] text-white/25 italic">
        Generated by Qwen3.5-35B on DGX Spark. Verify all claims against source links.
      </p>
    </div>
  );
}
