/** One biome kit per world: sky, fog, light and the flat block palette. Every world must read as a different place. */
import { B, type BiomeId, type BiomeKit, type BlockId } from "../types";

const kit = (k: BiomeKit) => k;

export const BIOMES: Record<BiomeId, BiomeKit> = {
  factory: kit({
    id: "factory",
    sky: "#7ec8ff",
    skyLow: "#e4f4ff",
    fog: "#c6e6ff",
    fogNear: 45,
    fogFar: 120,
    ambient: 1.6,
    sun: 2.2,
    blocks: {
      [B.solid]: "#8f9ab0",
      [B.solid2]: "#ffc63a",
      [B.trim]: "#ff7a1a",
      [B.bounce]: "#ffd23a",
      [B.crumble]: "#c3c9d6",
      [B.ice]: "#c9ecff",
      [B.glass]: "#dff6ff",
      [B.door]: "#ff5a3c",
      [B.switchBase]: "#2f3542",
      [B.conveyorN]: "#3a3f4a",
      [B.conveyorE]: "#3a3f4a",
      [B.conveyorS]: "#3a3f4a",
      [B.conveyorW]: "#3a3f4a",
      [B.pillar]: "#59d8ff",
      [B.glow]: "#ffe66d",
      [B.spike]: "#e6ebf2",
      [B.goo]: "#ff7a1a",
      [B.wall]: "#5d6577",
      [B.star]: "#fff1a8",
      [B.bridge]: "#59d8ff",
    },
    tagline: "A tiny hero. A very big rescue.",
  }),
  void: kit({
    id: "void",
    sky: "#000000",
    skyLow: "#000000",
    fog: null,
    fogNear: 0,
    fogFar: 0,
    ambient: 1.2,
    sun: 1.4,
    blocks: {
      [B.solid]: "#ffe066",
      [B.solid2]: "#ffb3ff",
      [B.star]: "#fff6a3",
      [B.trim]: "#7de3ff",
      [B.door]: "#ff6ad5",
      [B.glow]: "#ffffff",
      [B.crumble]: "#d9c86a",
      [B.bounce]: "#a8ffdf",
      [B.wall]: "#2d2660",
      [B.switchBase]: "#3a2f7a",
      [B.goo]: "#3a0a5a",
    },
    tagline: "Make a friend among the stars.",
  }),
  clouds: kit({
    id: "clouds",
    sky: "#7fb8ff",
    skyLow: "#ffffff",
    fog: "#dbe9ff",
    fogNear: 35,
    fogFar: 130,
    ambient: 1.8,
    sun: 2.4,
    blocks: {
      [B.solid]: "#ffffff",
      [B.solid2]: "#bfe0ff",
      [B.crumble]: "#eef6ff",
      [B.bounce]: "#ffd6f0",
      [B.trim]: "#ffd97a",
      [B.door]: "#ff9ad5",
      [B.glow]: "#fff7c2",
      [B.wall]: "#a9c8ff",
      [B.switchBase]: "#7fa3d9",
    },
    tagline: "A leap into the wonderful.",
  }),
  underwater: kit({
    id: "underwater",
    sky: "#0b4c8a",
    skyLow: "#082f5a",
    fog: "#0b4c8a",
    fogNear: 8,
    fogFar: 42,
    ambient: 1.3,
    sun: 1.6,
    blocks: {
      [B.solid]: "#e6c96b",
      [B.solid2]: "#ff7ab8",
      [B.trim]: "#4be3c8",
      [B.spike]: "#ff4d4d",
      [B.water]: "#1f8fff",
      [B.door]: "#ffb347",
      [B.glow]: "#9dfff0",
      [B.wall]: "#2b6ea3",
      [B.switchBase]: "#245a80",
      [B.glass]: "#bff3ff",
    },
    tagline: "Dive into a sea of surprises.",
  }),
  pipes: kit({
    id: "pipes",
    sky: "#9fe6a0",
    skyLow: "#eaffdf",
    fog: "#c9f5c2",
    fogNear: 35,
    fogFar: 115,
    ambient: 1.6,
    sun: 2.2,
    blocks: {
      [B.solid]: "#2fbf5a",
      [B.solid2]: "#1e8f45",
      [B.trim]: "#e0b13a",
      [B.glass]: "#d6ffe0",
      [B.door]: "#e0b13a",
      [B.goo]: "#7a4b1e",
      [B.wall]: "#166b34",
      [B.switchBase]: "#b8882a",
      [B.bounce]: "#ffe36b",
    },
    tagline: "Where does this pipe go?",
  }),
  bouncy: kit({
    id: "bouncy",
    sky: "#ff8fd0",
    skyLow: "#ffe6f5",
    fog: "#ffc2e5",
    fogNear: 35,
    fogFar: 115,
    ambient: 1.7,
    sun: 2.3,
    blocks: {
      [B.solid]: "#ff4fa3",
      [B.solid2]: "#ffd23a",
      [B.bounce]: "#ffe36b",
      [B.trim]: "#6ff1da",
      [B.door]: "#6ff1da",
      [B.wall]: "#b8297a",
      [B.switchBase]: "#8a1f5c",
      [B.crumble]: "#ffb0d8",
    },
    tagline: "The floor has a spring in its step.",
  }),
  danger: kit({
    id: "danger",
    sky: "#2a0f14",
    skyLow: "#6a1e24",
    fog: "#3a1218",
    fogNear: 25,
    fogFar: 95,
    ambient: 1.1,
    sun: 1.8,
    blocks: {
      [B.solid]: "#3b3f4a",
      [B.solid2]: "#ff2d2d",
      [B.trim]: "#ffd400",
      [B.spike]: "#ff5a5a",
      [B.goo]: "#ff3b00",
      [B.door]: "#ffd400",
      [B.glow]: "#ff8a3b",
      [B.wall]: "#22242c",
      [B.switchBase]: "#1a1c22",
      [B.crumble]: "#6b6f7a",
    },
    tagline: "Watch. Wait. Make your move.",
  }),
  candy: kit({
    id: "candy",
    sky: "#ffb3e6",
    skyLow: "#fff3fa",
    fog: "#ffd3ec",
    fogNear: 35,
    fogFar: 115,
    ambient: 1.7,
    sun: 2.2,
    blocks: {
      [B.solid]: "#ffd1dc",
      [B.solid2]: "#ff4f7d",
      [B.trim]: "#ffffff",
      [B.goo]: "#7a3b1e",
      [B.bounce]: "#ffe36b",
      [B.ice]: "#bff0ff",
      [B.door]: "#8de3ff",
      [B.wall]: "#e07aa8",
      [B.switchBase]: "#a8455f",
      [B.crumble]: "#ffe8ef",
    },
    tagline: "Sweet world. Tricky surprises.",
  }),
  dark: kit({
    id: "dark",
    sky: "#02020a",
    skyLow: "#06061c",
    fog: "#03030f",
    fogNear: 6,
    fogFar: 30,
    ambient: 0.35,
    sun: 0.5,
    blocks: {
      [B.solid]: "#1c1c40",
      [B.solid2]: "#2c2c62",
      [B.trim]: "#8dff9d",
      [B.glow]: "#b4ffed",
      [B.flip]: "#c86bff",
      [B.spike]: "#ff4d9d",
      [B.door]: "#8dff9d",
      [B.wall]: "#0d0d24",
      [B.switchBase]: "#3d2f6a",
    },
    tagline: "Stay close. Cubo knows the way.",
  }),
  between: kit({
    id: "between",
    sky: "#2b1b52",
    skyLow: "#0d0620",
    fog: "#3a2b6a",
    fogNear: 25,
    fogFar: 100,
    ambient: 1.4,
    sun: 1.8,
    blocks: {
      [B.solid]: "#8f5bff",
      [B.solid2]: "#ff3bd4",
      [B.trim]: "#3bffea",
      [B.glass]: "#ffffff",
      [B.door]: "#3bffea",
      [B.wall]: "#3a2470",
      [B.switchBase]: "#22124a",
      [B.crumble]: "#c9a8ff",
    },
    tagline: "One last hop. Everybody comes home.",
  }),
};

export function blockColor(kit: BiomeKit, id: BlockId): string {
  return kit.blocks[id] ?? kit.blocks[B.solid];
}
