#!/usr/bin/env python3
"""
Convert HEIC wedding photos -> WebP triplets for /e-and-t.

    src: /home/jelly/Shared/wedding/*.HEIC
    out: public/e-and-t/photos/{id}-{800,1600,2400}.webp
    emit: components/wedding/data/photos.ts (typed manifest w/ blurDataURL)

Uses pillow + pillow_heif because the system libvips/heif-convert cannot
decode iPhone Air HEVC10 HDR HEIC files on this box. Idempotent: re-run after
dropping new HEICs in the source folder.
"""
import base64
import io
import json
import os
import sys
from pathlib import Path

from PIL import Image
import pillow_heif

pillow_heif.register_heif_opener()

SRC_DIR = Path("/home/jelly/Shared/wedding")
OUT_DIR = Path("/home/jelly/tolley-site/public/e-and-t/photos")
MANIFEST = Path("/home/jelly/tolley-site/components/wedding/data/photos.ts")
SIZES = (800, 1600, 2400)

OUT_DIR.mkdir(parents=True, exist_ok=True)

heics = sorted(
    p for p in SRC_DIR.iterdir()
    if p.suffix.lower() == ".heic" and not p.name.startswith("._")
)

if not heics:
    print(f"No HEIC files in {SRC_DIR}", file=sys.stderr)
    sys.exit(1)

manifest = []

for i, heic in enumerate(heics, start=1):
    photo_id = heic.stem.lower()
    print(f"[{i}/{len(heics)}] {heic.name}")
    img = Image.open(heic)
    # Auto-orient via EXIF
    try:
        from PIL import ImageOps
        img = ImageOps.exif_transpose(img)
    except Exception:
        pass

    if img.mode not in ("RGB", "RGBA"):
        img = img.convert("RGB")

    base_w, base_h = img.size
    if base_w == 0 or base_h == 0:
        raise RuntimeError(f"bad dims for {heic}")

    for w in SIZES:
        if w >= base_w:
            scaled = img.copy()
        else:
            ratio = w / base_w
            scaled = img.resize((w, int(round(base_h * ratio))), Image.LANCZOS)
        out = OUT_DIR / f"{photo_id}-{w}.webp"
        scaled.save(out, "WEBP", quality=82, method=6)
        size_kb = out.stat().st_size / 1024
        print(f"    {out.name}  {size_kb:.0f}kb")

    # 16px blur preview as base64 data URL
    blur = img.copy()
    blur.thumbnail((16, 16), Image.LANCZOS)
    buf = io.BytesIO()
    blur.save(buf, "WEBP", quality=30, method=6)
    blur_data_url = "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode()

    manifest.append({
        "id": photo_id,
        "width": base_w,
        "height": base_h,
        "ratio": base_w / base_h,
        "blurDataURL": blur_data_url,
        "alt": f"Emily & Trevor — moment {i}",
        "span": 2 if (i - 1) % 3 == 0 else 1,
    })

ts = (
    "// AUTOGENERATED by scripts/convert-wedding-photos.py — do not edit by hand.\n"
    "// Re-run after dropping new HEICs into /home/jelly/Shared/wedding/.\n\n"
    "export type WeddingPhoto = {\n  id: string;\n  width: number;\n  height: number;\n"
    "  ratio: number;\n  blurDataURL: string;\n  alt: string;\n  span?: 1 | 2;\n};\n\n"
    "export const PHOTOS: WeddingPhoto[] = "
    + json.dumps(manifest, indent=2)
    + ";\n"
)
MANIFEST.write_text(ts)
print(f"\nWrote manifest: {MANIFEST} ({len(manifest)} photos)")
