/**
 * Convert HEIC wedding photos → WebP triplets for /e-and-t.
 *
 *   src: /home/jelly/Shared/wedding/*.HEIC
 *   out: public/e-and-t/photos/{id}-{800,1600,2400}.webp
 *   emit: components/wedding/data/photos.ts (typed manifest w/ blurDataURL)
 *
 * Sharp reads HEIF/HEIC natively on this libvips build, so we go HEIC → WebP
 * in one step at three widths + a 16px base64 blur preview for next/image.
 * Idempotent: drop new HEICs in the source folder and re-run.
 */

import { mkdirSync, readdirSync, writeFileSync, statSync } from "node:fs";
import { join, basename } from "node:path";
import sharp from "sharp";

const SRC_DIR = "/home/jelly/Shared/wedding";
const OUT_DIR = "/home/jelly/tolley-site/public/e-and-t/photos";
const MANIFEST = "/home/jelly/tolley-site/components/wedding/data/photos.ts";
const SIZES = [800, 1600, 2400] as const;

type PhotoEntry = {
  id: string;
  ratio: number;
  width: number;
  height: number;
  blurDataURL: string;
  alt: string;
  span?: 1 | 2;
};

async function main() {
  mkdirSync(OUT_DIR, { recursive: true });

  const heics = readdirSync(SRC_DIR)
    .filter((f) => /\.heic$/i.test(f) && !f.startsWith("._"))
    .sort();

  if (heics.length === 0) {
    console.error(`No HEIC files in ${SRC_DIR}`);
    process.exit(1);
  }

  const manifest: PhotoEntry[] = [];

  for (let i = 0; i < heics.length; i++) {
    const heic = heics[i];
    const id = basename(heic, ".HEIC").replace(/\.heic$/i, "").toLowerCase();
    const src = join(SRC_DIR, heic);
    console.log(`[${i + 1}/${heics.length}] ${heic}`);

    const meta = await sharp(src).rotate().metadata();
    const baseW = meta.width ?? 0;
    const baseH = meta.height ?? 0;
    if (!baseW || !baseH) throw new Error(`Bad dims for ${heic}`);

    for (const w of SIZES) {
      const out = join(OUT_DIR, `${id}-${w}.webp`);
      await sharp(src)
        .rotate()
        .resize({ width: w, withoutEnlargement: true })
        .webp({ quality: 82 })
        .toFile(out);
      const stat = statSync(out);
      console.log(`    ${id}-${w}.webp  ${(stat.size / 1024).toFixed(0)}kb`);
    }

    const blurBuf = await sharp(src).rotate().resize(16).webp({ quality: 30 }).toBuffer();
    const blurDataURL = `data:image/webp;base64,${blurBuf.toString("base64")}`;

    manifest.push({
      id,
      width: baseW,
      height: baseH,
      ratio: baseW / baseH,
      blurDataURL,
      alt: `Emily & Trevor — moment ${i + 1}`,
      span: i % 3 === 0 ? 2 : 1,
    });
  }

  const ts =
    `// AUTOGENERATED by scripts/convert-wedding-photos.ts — do not edit by hand.\n` +
    `// Re-run after dropping new HEICs into /home/jelly/Shared/wedding/.\n\n` +
    `export type WeddingPhoto = {\n  id: string;\n  width: number;\n  height: number;\n  ratio: number;\n  blurDataURL: string;\n  alt: string;\n  span?: 1 | 2;\n};\n\n` +
    `export const PHOTOS: WeddingPhoto[] = ${JSON.stringify(manifest, null, 2)};\n`;

  writeFileSync(MANIFEST, ts);
  console.log(`\nWrote manifest: ${MANIFEST} (${manifest.length} photos)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
