const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();

const HOUSEHOLD_ID = 'cmmz8yy560001l49tlyfsbymc';

function slug(title) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

const recipes = [
  // === CHINESE ===
  {
    title: 'Beef and Broccoli Stir Fry',
    description: 'Better than takeout — tender beef strips and crisp broccoli in a savory brown sauce.',
    cuisine: 'Chinese',
    mealType: ['dinner'],
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    tags: ['quick', 'kid-friendly', 'stir-fry'],
    ingredients: [
      { name: 'flank steak', quantity: 1, unit: 'lb', notes: 'thinly sliced against the grain' },
      { name: 'broccoli florets', quantity: 4, unit: 'cups' },
      { name: 'soy sauce', quantity: 0.25, unit: 'cup' },
      { name: 'oyster sauce', quantity: 2, unit: 'tbsp' },
      { name: 'sesame oil', quantity: 1, unit: 'tbsp' },
      { name: 'cornstarch', quantity: 2, unit: 'tbsp' },
      { name: 'garlic', quantity: 4, unit: 'cloves', notes: 'minced' },
      { name: 'fresh ginger', quantity: 1, unit: 'tsp', notes: 'grated' },
      { name: 'brown sugar', quantity: 1, unit: 'tbsp' },
      { name: 'beef broth', quantity: 0.5, unit: 'cup' },
      { name: 'vegetable oil', quantity: 2, unit: 'tbsp' },
      { name: 'white rice', quantity: 2, unit: 'cups', notes: 'cooked, for serving' },
    ],
    instructions: [
      { step: 1, text: 'Mix soy sauce, oyster sauce, sesame oil, brown sugar, beef broth, and 1 tbsp cornstarch in a bowl. Set aside.', duration: '3 min' },
      { step: 2, text: 'Toss sliced beef with remaining 1 tbsp cornstarch until coated.', duration: '2 min' },
      { step: 3, text: 'Heat oil in a large skillet or wok over high heat. Add beef in a single layer and cook 2-3 minutes per side until browned. Remove beef and set aside.', duration: '6 min' },
      { step: 4, text: 'In same pan, add garlic and ginger, stir 30 seconds. Add broccoli and stir fry 3-4 minutes until bright green and tender-crisp.', duration: '5 min' },
      { step: 5, text: 'Return beef to pan, pour sauce over everything and toss to coat. Cook 1-2 more minutes until sauce thickens.', duration: '2 min' },
      { step: 6, text: 'Serve immediately over white rice.', duration: '1 min' },
    ],
    nutrition: { calories: 380, protein: 32, carbs: 28, fat: 14, fiber: 3 },
  },
  {
    title: 'Egg Fried Rice',
    description: 'Classic Chinese fried rice — fluffy eggs, peas, and carrots with perfectly seasoned day-old rice.',
    cuisine: 'Chinese',
    mealType: ['dinner', 'lunch'],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    tags: ['quick', 'kid-friendly', 'pantry-friendly', 'budget'],
    ingredients: [
      { name: 'cooked white rice', quantity: 4, unit: 'cups', notes: 'day-old preferred' },
      { name: 'eggs', quantity: 3, unit: 'large' },
      { name: 'frozen peas and carrots', quantity: 1, unit: 'cup', notes: 'thawed' },
      { name: 'soy sauce', quantity: 3, unit: 'tbsp' },
      { name: 'sesame oil', quantity: 1, unit: 'tsp' },
      { name: 'garlic', quantity: 2, unit: 'cloves', notes: 'minced' },
      { name: 'green onions', quantity: 3, unit: 'stalks', notes: 'sliced' },
      { name: 'vegetable oil', quantity: 2, unit: 'tbsp' },
      { name: 'white pepper', quantity: 0.25, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, text: 'Heat oil in a large wok or skillet over high heat until smoking.', duration: '2 min' },
      { step: 2, text: 'Add garlic and stir 30 seconds. Add peas and carrots, cook 2 minutes.', duration: '3 min' },
      { step: 3, text: 'Push vegetables to the side. Crack eggs into the pan and scramble until just set, then mix with vegetables.', duration: '2 min' },
      { step: 4, text: 'Add rice, breaking up any clumps. Stir fry on high heat for 3-4 minutes until rice is hot and slightly crispy.', duration: '4 min' },
      { step: 5, text: 'Add soy sauce, sesame oil, and white pepper. Toss to combine. Top with green onions.', duration: '1 min' },
    ],
    nutrition: { calories: 310, protein: 12, carbs: 48, fat: 8, fiber: 2 },
  },
  {
    title: 'Sweet and Sour Chicken',
    description: 'Crispy chicken chunks tossed in a tangy homemade sweet and sour sauce — no deep fryer needed.',
    cuisine: 'Chinese',
    mealType: ['dinner'],
    prepTime: 20,
    cookTime: 20,
    servings: 4,
    tags: ['kid-friendly', 'crowd-pleaser'],
    ingredients: [
      { name: 'chicken breast', quantity: 1.5, unit: 'lb', notes: 'cut into 1-inch cubes' },
      { name: 'cornstarch', quantity: 0.5, unit: 'cup' },
      { name: 'eggs', quantity: 2, unit: 'large', notes: 'beaten' },
      { name: 'bell pepper', quantity: 1, unit: 'large', notes: 'chopped into chunks' },
      { name: 'pineapple chunks', quantity: 1, unit: 'cup', notes: 'canned or fresh' },
      { name: 'ketchup', quantity: 0.25, unit: 'cup' },
      { name: 'rice vinegar', quantity: 3, unit: 'tbsp' },
      { name: 'sugar', quantity: 3, unit: 'tbsp' },
      { name: 'soy sauce', quantity: 1, unit: 'tbsp' },
      { name: 'vegetable oil', quantity: 0.25, unit: 'cup', notes: 'for pan frying' },
      { name: 'garlic', quantity: 2, unit: 'cloves', notes: 'minced' },
    ],
    instructions: [
      { step: 1, text: 'Mix sauce: ketchup, vinegar, sugar, soy sauce, and 2 tbsp pineapple juice. Set aside.', duration: '2 min' },
      { step: 2, text: 'Dip chicken in egg, then coat in cornstarch.', duration: '5 min' },
      { step: 3, text: 'Heat oil in skillet over medium-high. Fry chicken in batches 4-5 minutes per side until golden and cooked through. Drain on paper towels.', duration: '12 min' },
      { step: 4, text: 'Drain most oil, leaving 1 tbsp. Sauté garlic and bell pepper 2 minutes. Add pineapple.', duration: '3 min' },
      { step: 5, text: 'Pour in sauce, bring to a simmer 1 minute. Add chicken and toss to coat.', duration: '2 min' },
    ],
    nutrition: { calories: 420, protein: 36, carbs: 42, fat: 10, fiber: 1 },
  },
  {
    title: 'Chicken Lo Mein',
    description: 'Silky noodles with tender chicken, snap peas, and a savory sauce — ready faster than delivery.',
    cuisine: 'Chinese',
    mealType: ['dinner'],
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    tags: ['quick', 'noodles', 'kid-friendly'],
    ingredients: [
      { name: 'lo mein noodles', quantity: 8, unit: 'oz', notes: 'or spaghetti works too' },
      { name: 'chicken breast', quantity: 1, unit: 'lb', notes: 'thinly sliced' },
      { name: 'snap peas', quantity: 1, unit: 'cup' },
      { name: 'carrots', quantity: 2, unit: 'medium', notes: 'julienned' },
      { name: 'cabbage', quantity: 2, unit: 'cups', notes: 'shredded' },
      { name: 'soy sauce', quantity: 3, unit: 'tbsp' },
      { name: 'hoisin sauce', quantity: 2, unit: 'tbsp' },
      { name: 'sesame oil', quantity: 1, unit: 'tbsp' },
      { name: 'garlic', quantity: 3, unit: 'cloves', notes: 'minced' },
      { name: 'ginger', quantity: 1, unit: 'tsp', notes: 'grated' },
      { name: 'vegetable oil', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, text: 'Cook noodles per package directions, slightly underdone. Drain and toss with a little sesame oil.', duration: '8 min' },
      { step: 2, text: 'Mix sauce: soy sauce, hoisin, sesame oil.', duration: '1 min' },
      { step: 3, text: 'Heat oil over high heat. Stir fry chicken until cooked, about 4 minutes. Remove.', duration: '5 min' },
      { step: 4, text: 'Add garlic, ginger, carrots, cabbage, and snap peas. Stir fry 3 minutes.', duration: '3 min' },
      { step: 5, text: 'Add noodles, chicken, and sauce. Toss everything together on high heat for 2 minutes.', duration: '2 min' },
    ],
    nutrition: { calories: 445, protein: 34, carbs: 52, fat: 10, fiber: 4 },
  },
  {
    title: 'Chinese Chicken Soup with Ginger',
    description: 'Light, restorative chicken soup with ginger and green onion — great when someone feels under the weather.',
    cuisine: 'Chinese',
    mealType: ['dinner', 'lunch'],
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    tags: ['healthy', 'comfort-food', 'easy'],
    ingredients: [
      { name: 'chicken thighs', quantity: 1.5, unit: 'lb', notes: 'bone-in or boneless' },
      { name: 'chicken broth', quantity: 6, unit: 'cups' },
      { name: 'fresh ginger', quantity: 2, unit: 'inches', notes: 'sliced into coins' },
      { name: 'garlic', quantity: 4, unit: 'cloves', notes: 'smashed' },
      { name: 'green onions', quantity: 4, unit: 'stalks', notes: 'sliced' },
      { name: 'soy sauce', quantity: 2, unit: 'tbsp' },
      { name: 'sesame oil', quantity: 1, unit: 'tsp' },
      { name: 'rice noodles', quantity: 4, unit: 'oz', notes: 'optional' },
      { name: 'salt', quantity: 0.5, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, text: 'Combine broth, chicken, ginger, garlic in a pot. Bring to boil, then simmer 20 minutes.', duration: '22 min' },
      { step: 2, text: 'Remove chicken, shred, discard bones. Strain broth if desired.', duration: '5 min' },
      { step: 3, text: 'Return broth to simmer. If using noodles, add and cook per package.', duration: '5 min' },
      { step: 4, text: 'Add shredded chicken, soy sauce, sesame oil. Season with salt. Top with green onions.', duration: '2 min' },
    ],
    nutrition: { calories: 280, protein: 30, carbs: 18, fat: 9, fiber: 1 },
  },

  // === ITALIAN ===
  {
    title: 'Classic Spaghetti Bolognese',
    description: 'Rich, slow-simmered meat sauce clinging to al dente spaghetti — a Sunday dinner staple.',
    cuisine: 'Italian',
    mealType: ['dinner'],
    prepTime: 15,
    cookTime: 60,
    servings: 6,
    tags: ['comfort-food', 'crowd-pleaser', 'make-ahead'],
    ingredients: [
      { name: 'spaghetti', quantity: 1, unit: 'lb' },
      { name: 'ground beef', quantity: 1, unit: 'lb' },
      { name: 'ground pork', quantity: 0.5, unit: 'lb' },
      { name: 'onion', quantity: 1, unit: 'large', notes: 'diced' },
      { name: 'carrots', quantity: 2, unit: 'medium', notes: 'diced fine' },
      { name: 'celery', quantity: 2, unit: 'stalks', notes: 'diced fine' },
      { name: 'garlic', quantity: 4, unit: 'cloves', notes: 'minced' },
      { name: 'crushed tomatoes', quantity: 28, unit: 'oz', notes: 'one can' },
      { name: 'tomato paste', quantity: 2, unit: 'tbsp' },
      { name: 'whole milk', quantity: 0.5, unit: 'cup' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'dried oregano', quantity: 1, unit: 'tsp' },
      { name: 'bay leaf', quantity: 2, unit: 'whole' },
      { name: 'salt and pepper', quantity: 1, unit: 'to taste' },
      { name: 'parmesan cheese', quantity: 0.5, unit: 'cup', notes: 'freshly grated, for serving' },
    ],
    instructions: [
      { step: 1, text: 'Heat olive oil over medium. Sauté onion, carrots, celery until soft, about 8 minutes.', duration: '8 min' },
      { step: 2, text: 'Add garlic, cook 1 minute. Add beef and pork, breaking up, cook until browned.', duration: '8 min' },
      { step: 3, text: 'Stir in tomato paste, cook 2 minutes. Add crushed tomatoes, oregano, bay leaves.', duration: '3 min' },
      { step: 4, text: 'Pour in milk and stir. Reduce heat to low, simmer uncovered 45-60 minutes, stirring occasionally.', duration: '60 min' },
      { step: 5, text: 'Cook pasta al dente. Toss with sauce, top with parmesan.', duration: '10 min' },
    ],
    nutrition: { calories: 580, protein: 38, carbs: 62, fat: 18, fiber: 5 },
  },
  {
    title: 'Chicken Piccata',
    description: 'Tender pan-fried chicken in a bright lemon-caper butter sauce — fancy enough for guests, easy enough for Tuesday.',
    cuisine: 'Italian',
    mealType: ['dinner'],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    tags: ['quick', 'elegant', 'lemon'],
    ingredients: [
      { name: 'chicken breast', quantity: 4, unit: 'pieces', notes: 'pounded thin or butterflied' },
      { name: 'all-purpose flour', quantity: 0.5, unit: 'cup' },
      { name: 'butter', quantity: 4, unit: 'tbsp' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'lemon juice', quantity: 0.25, unit: 'cup', notes: 'fresh' },
      { name: 'chicken broth', quantity: 0.5, unit: 'cup' },
      { name: 'capers', quantity: 3, unit: 'tbsp', notes: 'drained' },
      { name: 'fresh parsley', quantity: 2, unit: 'tbsp', notes: 'chopped' },
      { name: 'salt and pepper', quantity: 1, unit: 'to taste' },
    ],
    instructions: [
      { step: 1, text: 'Season chicken with salt and pepper, dredge in flour shaking off excess.', duration: '3 min' },
      { step: 2, text: 'Heat 2 tbsp butter + olive oil over medium-high. Cook chicken 3-4 min per side until golden. Remove and keep warm.', duration: '8 min' },
      { step: 3, text: 'Add broth and lemon juice to pan, scraping up browned bits. Simmer 2 minutes.', duration: '3 min' },
      { step: 4, text: 'Add capers and remaining 2 tbsp butter. Swirl until sauce is glossy.', duration: '2 min' },
      { step: 5, text: 'Return chicken to pan, coat in sauce, top with parsley. Serve with pasta or roasted potatoes.', duration: '1 min' },
    ],
    nutrition: { calories: 340, protein: 38, carbs: 12, fat: 16, fiber: 0 },
  },
  {
    title: 'Homemade Lasagna',
    description: 'Layers of rich meat sauce, creamy ricotta, and melty mozzarella — the ultimate make-ahead family meal.',
    cuisine: 'Italian',
    mealType: ['dinner'],
    prepTime: 30,
    cookTime: 60,
    servings: 8,
    tags: ['make-ahead', 'comfort-food', 'crowd-pleaser', 'freezer-friendly'],
    ingredients: [
      { name: 'lasagna noodles', quantity: 12, unit: 'sheets', notes: 'cooked al dente' },
      { name: 'ground beef', quantity: 1, unit: 'lb' },
      { name: 'Italian sausage', quantity: 0.5, unit: 'lb', notes: 'removed from casing' },
      { name: 'marinara sauce', quantity: 24, unit: 'oz', notes: 'jarred or homemade' },
      { name: 'ricotta cheese', quantity: 15, unit: 'oz' },
      { name: 'mozzarella cheese', quantity: 3, unit: 'cups', notes: 'shredded' },
      { name: 'parmesan cheese', quantity: 0.5, unit: 'cup', notes: 'grated' },
      { name: 'eggs', quantity: 2, unit: 'large' },
      { name: 'fresh parsley', quantity: 2, unit: 'tbsp', notes: 'chopped' },
      { name: 'garlic powder', quantity: 1, unit: 'tsp' },
      { name: 'salt and pepper', quantity: 1, unit: 'to taste' },
    ],
    instructions: [
      { step: 1, text: 'Brown beef and sausage. Drain fat. Stir in marinara, simmer 10 minutes.', duration: '15 min' },
      { step: 2, text: 'Mix ricotta, eggs, parsley, garlic powder, salt, pepper, and half the parmesan.', duration: '3 min' },
      { step: 3, text: 'Preheat oven to 375°F. Spread thin layer of meat sauce in 9x13 baking dish.', duration: '5 min' },
      { step: 4, text: 'Layer: noodles → ricotta mix → mozzarella → meat sauce. Repeat 3 times. Top with remaining mozzarella and parmesan.', duration: '10 min' },
      { step: 5, text: 'Cover with foil. Bake 45 minutes. Remove foil, bake 15 more minutes until bubbly and golden.', duration: '60 min' },
      { step: 6, text: 'Let rest 15 minutes before cutting.', duration: '15 min' },
    ],
    nutrition: { calories: 520, protein: 36, carbs: 38, fat: 24, fiber: 3 },
  },
  {
    title: 'Pasta e Fagioli',
    description: 'Hearty Italian peasant soup with pasta, cannellini beans, and tomatoes — thick, filling, and incredibly cheap to make.',
    cuisine: 'Italian',
    mealType: ['dinner', 'lunch'],
    prepTime: 10,
    cookTime: 30,
    servings: 6,
    tags: ['budget', 'healthy', 'pantry-friendly', 'comfort-food'],
    ingredients: [
      { name: 'ditalini pasta', quantity: 1, unit: 'cup', notes: 'or any small pasta' },
      { name: 'cannellini beans', quantity: 30, unit: 'oz', notes: 'two cans, drained' },
      { name: 'crushed tomatoes', quantity: 14, unit: 'oz', notes: 'one can' },
      { name: 'chicken broth', quantity: 4, unit: 'cups' },
      { name: 'onion', quantity: 1, unit: 'medium', notes: 'diced' },
      { name: 'garlic', quantity: 4, unit: 'cloves', notes: 'minced' },
      { name: 'celery', quantity: 2, unit: 'stalks', notes: 'diced' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'dried rosemary', quantity: 0.5, unit: 'tsp' },
      { name: 'dried thyme', quantity: 0.5, unit: 'tsp' },
      { name: 'parmesan rind', quantity: 1, unit: 'piece', notes: 'optional but adds great flavor' },
      { name: 'salt and pepper', quantity: 1, unit: 'to taste' },
    ],
    instructions: [
      { step: 1, text: 'Heat oil over medium. Sauté onion and celery until soft, 5 minutes. Add garlic and herbs, cook 1 minute.', duration: '6 min' },
      { step: 2, text: 'Add tomatoes, broth, parmesan rind if using. Bring to boil.', duration: '5 min' },
      { step: 3, text: 'Mash half the beans, add to pot along with whole beans. Simmer 15 minutes.', duration: '15 min' },
      { step: 4, text: 'Add pasta and cook until al dente, about 8 minutes. Remove parmesan rind.', duration: '8 min' },
      { step: 5, text: 'Season with salt and pepper. Drizzle with olive oil to serve.', duration: '1 min' },
    ],
    nutrition: { calories: 310, protein: 16, carbs: 48, fat: 6, fiber: 10 },
  },
];

async function seed() {
  let added = 0;
  let skipped = 0;
  for (const r of recipes) {
    const s = slug(r.title);
    const existing = await p.foodRecipe.findUnique({ where: { householdId_slug: { householdId: HOUSEHOLD_ID, slug: s } } });
    if (existing) { console.log(`SKIP: ${r.title}`); skipped++; continue; }
    await p.foodRecipe.create({
      data: {
        householdId: HOUSEHOLD_ID,
        title: r.title,
        slug: s,
        description: r.description,
        cuisine: r.cuisine,
        mealType: r.mealType,
        prepTime: r.prepTime,
        cookTime: r.cookTime,
        servings: r.servings,
        tags: r.tags,
        ingredients: r.ingredients,
        instructions: r.instructions,
        nutrition: r.nutrition,
        rating: 0,
        timesCooked: 0,
        aiGenerated: false,
      }
    });
    console.log(`ADD: ${r.title}`);
    added++;
  }
  console.log(`\nDone. Added: ${added}, Skipped: ${skipped}`);
}

seed().catch(console.error).finally(() => p.$disconnect());
