CREATE TABLE "DgxActivity" (
    "id" INTEGER NOT NULL DEFAULT 1,
    "line" TEXT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DgxActivity_pkey" PRIMARY KEY ("id")
);
